### ISSUE TITLE
confiugre error syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by sunxinsara** [mtrojnar/osslsigncode#100]
I have followed the building manual
  ./autogen.sh
  ./configure

I got error when running "./configure"
./configure: line 4907: syntax error near unexpected token `newline'
./configure: line 4907: `PKG_CHECK_MODULES('

Any help is much appreciated.

**Comment by sunxinsara** [comment]
I've done these steps too, but the errors are still here.

On Linux, (tested on Debian/Ubuntu) you may need sudo apt-get update && sudo apt-get install build-essential autoconf libtool libssl-dev python3-pkgconfig libcurl4-gnutls-dev

**Comment by olszomal** [comment]
Setting the ACLOCAL_PATH environment variable before running the autogen.sh script should help.

`$ aclocal --print-ac-dir`
gives me
`/usr/share/aclocal`
therefore
`$ ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh`
`$ ./configure`

**Comment by sunxinsara** [comment]
Thanks for your reply! 
I have tried your advisment. but it does not work for me, problems just as before。
Now I am trying to delete the error block (PKG_CHECK_MODULES( something about openssl) & PKG_CHECK_MODULES( something about libcurl) and libcurl check ). 
And then the ./configure step can be done successfully.
I wish I could fix next problems in make step. (faild in including openssl & libcurl)
Still working on it...

I think this method is a bit stupid...
will there be an easier way?

**Comment by sunxinsara** [comment]
> Setting the ACLOCAL_PATH environment variable before running the autogen.sh script should help.
> 
> `$ aclocal --print-ac-dir`
> gives me
> `/usr/share/aclocal`
> therefore
> `$ ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh`
> `$ ./configure`
Thanks for your reply!
I have tried your advisment. but it does not work for me, problems just as before。
Now I am trying to delete the error block (PKG_CHECK_MODULES( something about openssl) & PKG_CHECK_MODULES( something about libcurl) and libcurl check ).
And then the ./configure step can be done successfully.
I wish I could fix next problems in make step. (faild in including openssl & libcurl)
Still working on it...

I think this method is a bit stupid...
will there be an easier way?

**Comment by sunxinsara** [comment]
> Setting the ACLOCAL_PATH environment variable before running the autogen.sh script should help.
> 
> `$ aclocal --print-ac-dir`
> gives me
> `/usr/share/aclocal`
> therefore
> `$ ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh`
> `$ ./configure`



Thanks for your reply!
I have tried your advisment. but it does not work for me, problems just as before。
Now I am trying to delete the error block (PKG_CHECK_MODULES( something about openssl) & PKG_CHECK_MODULES( something about libcurl) and libcurl check ).
And then the ./configure step can be done successfully.
I wish I could fix next problems in make step. (faild in including openssl & libcurl)
Still working on it...

I think this method is a bit stupid...
will there be an easier way?

**Comment by olszomal** [comment]
Could you try `autoreconf --verbose --install --force` 
instead of `./autogen.sh` ?

**Comment by sunxinsara** [comment]
> Could you try `autoreconf --verbose --install --force`
> instead of `./autogen.sh` ?


I got some other errors.
```
configure.ac:59: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:71: error: possibly undefined macro: AC_CHECK_LIB
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by olszomal** [comment]
Have you got installed `pkg-config` package?
You may need to install the `autoconf-archive` package.

**Comment by sunxinsara** [comment]
> Have you got installed `pkg-config` package?
> You may need to install the `autoconf-archive` package.


It seems doesn't work for me 
```
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ sudo apt-get install pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 284 not upgraded.
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ sudo apt-get install autoconf-archive
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf-archive is already the newest version (20170928-2).
0 upgraded, 0 newly installed, 0 to remove and 284 not upgraded.
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ autoreconf --verbose --install --force
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:59: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:71: error: possibly undefined macro: AC_CHECK_LIB
autoreconf: /usr/bin/autoconf failed with exit status: 1
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ ACLOCAL_PATH=/usr/local/share/aclocal ./autogen.sh
Preparing the osslsigncode build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.16
Found GNU Libtool version 2.4.6

Automatically preparing build ... Warning: autoreconf failed
Attempting to run the preparation steps individually

Preparing build ... 
Warning: autoconf seems to have succeeded by removing the following options:
        AUTOCONF_OPTIONS="-f"

Removing those options should not be necessary and indicate some other
problem with the build system.  The build preparation is highly suspect
and may result in configuration or compilation errors.  Consider
rerunning the build preparation with verbose output enabled.
        ./autogen.sh --verbose

Continuing build preparation ... done

The osslsigncode build system is now prepared.  To build here, run:
  ./configure
  make
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
./configure: line 4317: PKG_PROG_PKG_CONFIG: command not found
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking whether make sets $(MAKE)... (cached) yes
checking for an ANSI C-conforming const... yes
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for dlopen in -ldl... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for getpass... yes
./configure: line 4906: syntax error near unexpected token `newline'
./configure: line 4906: `PKG_CHECK_MODULES('
sunxin@DESKTOP-2KPP7VC:~/osslsigncode$ 
```

**Comment by sunxinsara** [comment]
Hi, I think maybe something is wrong with ubuntu18.04. 
Everything goes well, when I change to ubuntu20.04.
