### ISSUE TITLE
Signing catalog ".cat"  files

### ISSUE THREAD

**Issue by alexivkin** [mtrojnar/osslsigncode#104]
This is a feature request to support signing cabs, much like signtool does. The osslsigncode "verify" command works well already on cabs

**Comment by olszomal** [comment]
osslsigncode 2.1 release supports CAB files signature.
The CAT files support feature is implemented, but not released yet.

**Comment by mtrojnar** [comment]
@alexivkin Have you tried the current master?

**Comment by alexivkin** [comment]
I could not use 2.1 earlier because of https://github.com/mtrojnar/osslsigncode/issues/98 but tried it with the workaround and it worked. Thank you!
