### ISSUE TITLE
Difference between -t and -ts in "sign" command not clear

### ISSUE THREAD

**Issue by marians** [mtrojnar/osslsigncode#105]
The help text for the `sign` command shows:

```nohighlight
-t                      = specifies that the digital signature will be timestamped
                          by the Time-Stamp Authority (TSA) indicated by the URL
                          this option cannot be used with the -ts option
-ts                     = specifies the URL of the RFC 3161 Time-Stamp Authority server
                          this option cannot be used with the -t option
```

From these explanations, I don't understand what the difference is. What's the difference between a TSA and an RFC 3161 TSA server?

**Comment by ebourg** [comment]
There are two timestamping protocols, the standard RFC 3161 protocol and an older Microsoft specific protocol. Most timestamping endpoints support both, so it doesn't really matter.

**Comment by olszomal** [comment]
[Microsoft Time Stamping](https://docs.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures)
[RFC 3161](https://www.ietf.org/rfc/rfc3161.txt)
This issue may be closed.

**Comment by marians** [comment]
For the future user, the help text on these flags might be improved to fully answer that question.
