### ISSUE TITLE
osslsigncode with AWS CloudHSM?

### ISSUE THREAD

**Issue by MrAlex94** [mtrojnar/osslsigncode#106]
Hi,

Has anyone managed to successfully utilise osslsigncode and AWS CloudHSM together? Amazon have instructions for [signtool](https://aws.amazon.com/blogs/security/signing-executables-with-microsoft-signtool-exe-using-aws-cloudhsm-backed-certificates/), which is simple enough to follow and I'm able to sign properly.

I feel as if I'm close on Linux but am not quite there.

On Ubuntu 16 LTS, I have:

* Built and installed OpenSSL 1.1.1c:
```
openssl version -a
OpenSSL 1.1.1c  28 May 2019
built on: Thu Feb 25 06:49:47 2021 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
Seeding source: os-specific
```
* Built and installed libp11-0.4.11 which output the libs we want in `/usr/local/ssl/lib/engines-1.1`. 

The results of `pkcs11-tool` give:

```bash
pkcs11-tool --module /opt/cloudhsm/lib/libcloudhsm_pkcs11.so --list-slots
Available slots:
Slot 0 (0x1): Cavium Slot
  token label        : cavium
  token manufacturer : Cavium Networks
  token model        : NITROX-III CNN35
  token flags        : login required, token initialized, PIN initialized
  hardware version   : 5.3
  firmware version   : 2.4
  serial num         : {SERIAL}
  pin min/max        : {MIN/MAX}
```
The latest necessary CLI tools are installed:
`cloudhsm-client-pkcs11 (3.3.1-1)`
`cloudhsm-client (3.3.1-1)`
The necessary service is live:
```
sudo service cloudhsm-client status
● cloudhsm-client.service - AWS CloudHsm Client daemon
   Loaded: loaded (/lib/systemd/system/cloudhsm-client.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-06-15 14:40:31 UTC; 1h 31min ago
     Docs: https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html
 Main PID: 25603 (cloudhsm_client)
    Tasks: 4
   Memory: 3.5M
      CPU: 4min 27.017s
   CGroup: /system.slice/cloudhsm-client.service
           └─25603 /opt/cloudhsm/bin/cloudhsm_client /opt/cloudhsm/etc/cloudhsm_client.cfg
```
The cluster certificate lives at:
`/opt/cloudhsm/etc/customerCA.crt`

When I try to sign though:
```
 osslsigncode sign \
>     -pkcs11engine /usr/local/ssl/lib/engines-1.1/pkcs11.so \
>     -pkcs11module /opt/cloudhsm/lib/libcloudhsm_pkcs11.so \
>     -pkcs11cert 'pkcs11:token=cavium;object=cert' \
>     -key 'pkcs11:token=cavuium;object=key' \
>     -in input.exe -out output.exe
Engine "pkcs11" set.
Enter PKCS#11 token PIN for cavium:
Certificate not found.
Failed to load certificate pkcs11:token=cavium;object=cert
139688091965248:error:80066065:pkcs11 engine:ctx_ctrl_load_cert:object not found:eng_back.c:652:
Failed
```
As the error outputs - it's clear there isn't a cert/private key living in the HSM.

I _thought_ I had some, as per following the AWS guide - but clearly not.

On Windows, [these steps](https://docs.aws.amazon.com/cloudhsm/latest/userguide/signtool-csr.html) create the certificate and key to sign with.

I feel like this may not be exactly related to osslsigncode - and may just be an issue to fix on my end.

I'm assuming I need to purchase an EV codesign certificate for HSM and somehow put the cert on the HSM (I haven't found *any* instructions on how that works). 

Has anyone gotten osslsigncode to work in this way?

Feel free to close if it's not the right place for this :-)

**Comment by edwardsb** [comment]
@MrAlex94 were you able to figure this out? Any notes would be appreciated.

**Comment by ZachNo** [comment]
For anyone viewing later, I was able to get this working after creating a CSR against the CloudHSM (used a Windows machine with Client 3.x installed), and having a certificate generated against that CSR. The cert doesn't live in the HSM, but when running the command to generate the CSR request, a public and private key are automatically generated in the user's CloudHSM. You can then use the certificate made using ```-certs``` and reference the automatically generated key using ```'pkcs11:token=hsm1[or whatever label your token provider has];object=[what ever the key label is]'```
