### ISSUE TITLE
Issue with rfc3161

### ISSUE THREAD

**Issue by setupdev** [mtrojnar/osslsigncode#109]
Hi,

I have an issue signing with rfc3161 timestamps when signing files. Timestamp with older authenticode standard works fine. I don't know if it is my environment or if I'm doing something stupid. I've tried on several different machines with CentOS 7 with osslsigncode v 1.7.1 and and CentOS 8 with version 2.1. 

We have successfully used version osslsigncode 1.7.1 on CentOS 7 for a couple of years. Thanks a lot to authors, btw. We sign using a private authenticode certificate and we have used the older authenticode timestamp method (with -t option). This has worked fine. 

Now many TSAs are changing to rfc3161 (without offering the older standard), so it would be good to begin using the newer standard, but I cannot get this to work. Here is the error output when I use the -ts option:

$ osslsigncode sign -verbose -certs demo.authenticode.spc -key demo.authenticode.key -n Mysoftware -h sha256 -ts http://timestamp.sectigo.com -verbose -in test.cab -out test.signed.cab
Failed to convert timestamp reply from http://timestamp.sectigo.com; HTTP status 404
139906608410688:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:
139906608410688:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:309:Type=TimeStampResp
RFC 3161 timestamping failed
Failed

The above command works as soon as I change to -t parameter. Do you have any idea from the error message where I could start looking?

**Comment by setupdev** [comment]
HTTP 404, you are right. But I don't understand why -t works with same address. I've tried multiple services and found that a couple are working with -t, but none with -ts. I wonder if our proxy is playing me here. I have to try it outside the proxy. 

I haven't reported a problem with 2.2. I'm not sure what you mean.

**Comment by setupdev** [comment]
OK, tested outside proxy (so officially overrode corporate cyber security), so this was all a proxy issue. Somehow it doesn't like the RFC 3161 http traffic then. We can close this ticket. Sorry for the noise.

**Comment by mtrojnar** [comment]
You mentioned 1.7.1 and 2.1, which are both not the latest version of osslsigncode. I only tried to make sure that you can reproduce this issue against the current master or the latest release (2.2).

**Comment by setupdev** [comment]
Ok, thanks. Now 2.1 worked fine outside our proxy, so I trust 2.2 will work just as fine.
