### ISSUE TITLE
Windows cannot verify the digital signature for this file

### ISSUE THREAD

**Issue by agoodhockey** [mtrojnar/osslsigncode#111]
In my CI/CD i need to sign my new driver.
My CI/CD system is on an Ubuntu machine.
The command line I use for signing is 
` ./osslsigncode sign -pkcs12 MY_PFX.pfx  -pass MY_PASSWORD -ac MY_CER.cer -in input_file.sys -out output_file.sys`
The output of the command is "Success".
But when i try to deploy my driver as a service it writes:
`Windows cannot verify the digital signature for this file ...`
Both the certificate and pfx files are valid and I know that because if I do the same with Microsoft's signtool.exe it works

I would appreciate if you could help :smile:

**Comment by olszomal** [comment]
The `osslsigncode sign` command returns "Success" if the file was successfully signed, but this command does not verify embedded signatures.
Does signtool verify your `sys` file signed with `osslsigncode`?
Does Windows can verify the whole certificate chain?
See this issue may help you https://github.com/mtrojnar/osslsigncode/issues/86

**Comment by agoodhockey** [comment]
Signtool cant verify the sys file signed with osslsigncode and it seems that windows cant verify the whole certificate chain. 
I looked into the issue you tagged and ran the same command line but it did not work, sadly.

**Comment by agoodhockey** [comment]
So, when I ran the command I noticed that I ran osslsigncode as an executable instead of a package. 

I compiled the code myself and ran it locally.
When I ran the code above as package it worked **BUT** when I ran osslsigncode as executable it wrote: 
```Windows cannot verify the digital signature for this file ...```

I think that some code changes in the repo "broke" the logic and caused the signing to be invalid. 
Also, seems like the package itself is not up to date with the code in the git. There are options that do not exist in the package. For example -st option.

**Comment by mtrojnar** [comment]
Do you mean the latest release of osslsigncode when you write "the package"? Did I correctly understand that th problem no longer occurs osslsigncode compiled from the current master branch? I highly recommend for you to read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html before replying.

**Comment by agoodhockey** [comment]
I managed to sign the driver. 
Seems like the problem was when i specified the flag -st (I use the source from master and not the release) 
When I used -st flag the driver was not signed correctly
