### ISSUE TITLE
OPENSSL_Uplink: no OPENSSL_Applink

### ISSUE THREAD

**Issue by mrihtar** [mtrojnar/osslsigncode#119]
In some cases I was getting the above error using your Windows build (2.2). With the following modification of osslsigncode.c
```
#include <openssl/applink.c>    // at the end of openssl includes
```
and compilation with msys2 mingw64 everything works fine.

**Comment by mtrojnar** [comment]
Interesting.  I could not reproduce this error.  You use osslsigncode.exe and *.dll from our osslsigncode 2.2 build (https://github.com/mtrojnar/osslsigncode/releases/download/2.2/osslsigncode_2.2_windows.zip), right?
What is your version of Windows?

**Comment by mtrojnar** [comment]
Please reopen when you can provide a way to reproduce it.
