### ISSUE TITLE
Build technique for both Linux and macOS?

### ISSUE THREAD

**Issue by rfay** [mtrojnar/osslsigncode#12]
I note that there's no documented way to build for macOS (and the homebrew version 1.7.1 doesn't seem to work any more).

I also note that this doesn't build as suggested in the readme on Linux (./configure)

Building hints appreciated.

**Comment by mtrojnar** [comment]
"doesn't seem to work" is hardly a helpful description of your problem.
Please bear in mind that osslsigncode currently requires OpenSSL 1.1.0 or later.

**Comment by rfay** [comment]
To be more specific, a windows binary signed with the macos Homebrew osslsigncode is not trusted on windows, even though the same version installed from linuxbew on Linux can sign windows binaries that are trusted on windows. The openssl requirement is an interesting possibility, perhaps the Homebrew formula is the issue.

Thanks for the good work on this, and looking forward to cross platform build techniques.

**Comment by mtrojnar** [comment]
Try investigating __why__ it is not trusted.  Does Windows recognize the file as signed?  Did you use the same key for signing on Homebrew and for signing on Linux?  See the "Digital Signature" tab in your Windows file properties.

**Comment by rfay** [comment]
Thanks. Now trying to recreate the issue I persistently ran into with signing the windows binary with Homebrew-osslsigncode on macOS I'm unable to recreate.

So for now let's keep this issue to the basic one: What is the correct build technique for mtrojnar/osslsigncode on Linux and macOS?

I'll be happy to do a PR with build instructions if you'll just outline them in this issue. Thanks! Again, thanks for your work on this critically important utility.

**Comment by rfay** [comment]
Ah, I see for Linux, the first thing is the instructions  in the README are missing the need to `./autogen.sh`, which is what creates the ./configure script.  (Sorry, it's been years since I've used automake and friends.)

In my case though (Ubuntu 18.04) the configure fails with `configure: error: OpenSSL 1.1.0 or later is required.` although `apt-get install openssl` gets `openssl is already the newest version (1.1.1c-1+ubuntu18.04.1+deb.sury.org+1)`

**Comment by mtrojnar** [comment]
Consider replacing:
```
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
```
with:
```
brew install pkg-config
```
I'd appreciate a PR.

**Comment by rfay** [comment]
PR in #15
