### ISSUE TITLE
curl version error 

### ISSUE THREAD

**Issue by javabeanz** [mtrojnar/osslsigncode#122]
configure halts with "configure: error: Curl 7.12.0 or later is required for timestamping support. http://curl.haxx.se/" while i have curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.45.1 OpenLDAP/2.4.59
please fix

**Comment by olszomal** [comment]
Could you try installing **libcurl-devel** package and confirm if the issue persists?
