### ISSUE TITLE
Centos cannot be installed

### ISSUE THREAD

**Issue by wutihong** [mtrojnar/osslsigncode#124]
![A6B79D47-5B63-47b8-AEF7-520E03F2F0D5](https://user-images.githubusercontent.com/24377930/147538742-ef9138e8-1da7-4d15-aabc-b8088e958804.png)
In centos7 or centos8 environment check has been unable to pass

Execution order：
1. yum install -y gcc
2. yum install -y openssl
3. yum install -y curl

In the end, the openssl version test failed, and the libcurl version did not pass.

**Comment by peterzhuamazon** [comment]
It can:
https://github.com/opensearch-project/opensearch-build/pull/3165
