### ISSUE TITLE
Authenticode timestamping failed

### ISSUE THREAD

**Issue by martinscholz83** [mtrojnar/osslsigncode#126]
When trying to sign exe with timestamp like this `-t http://sha256timestamp.ws.symantec.com/sha256/timestamp` i get the following error

```
Failed to convert timestamp reply from http://sha256timestamp.ws.symantec.com/sha256/timestamp; HTTP status 400
4450792960:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
Authenticode timestamping failed
Failed
```

Without timestamp signing is successful.

**Comment by olszomal** [comment]
Authenticode timestamping cannot be used for this Time Stamping Service. You should use RFC3161 timestamping. Try to change the parameter by adding `-ts` and forcing RFC3161.

**Comment by mtrojnar** [comment]
@olszomal Do you think we could add our user-friendly explanations to these cryptic OpenSSL errors?
