### ISSUE TITLE
Script variables issue when using pwsh 

### ISSUE THREAD

**Issue by Dr-Kristau** [mtrojnar/osslsigncode#144]
I'm using a simple test_sign.ps1 script on pwsh (PowerShell 7.2.2) on Fedora 35:
```
$pfx = "$PSScriptRoot/mykey.pfx"

function Use-SignTool($assemblyPath, $outPath)
{
	& osslsigncode sign -pkcs12 $pfx -pass mypassword -n "My Company 2022" -i http://www.mydomain.com -t http://timestamp.sectigo.com -in $assemblyPath -out $outPath
	Write-Output $pfx
	Write-Output $assemblyPath
	Write-Output $outPath
}

Use-SignTool("$PSScriptRoot/Unsigned/NETStandard.dll", "$PSScriptRoot/Signed/NETStandard.dll")
```
When I run this it fails:
```
PS /home/tofol/tmp> ./test_sign.ps1
Unknown option: /home/tofol/tmp/Signed/NETStandard.dll

Usage: /usr/local/bin/osslsigncode

 [ --version | -v ]

Failed
/home/tofol/tmp/mykey.pfx
/home/tofol/tmp/Unsigned/NETStandard.dll
/home/tofol/tmp/Signed/NETStandard.dll
```
But osslsigncode runs successfully if I copy these arguments directly into the PS cli:

```
PS /home/tofol/tmp> osslsigncode sign -pkcs12 /home/tofol/tmp/mykey.pfx -pass mypassword -n "My Company 2022" -i http://www.mydomain.com -t http://timestamp.sectigo.com -in /home/tofol/tmp/Unsigned/NETStandard.dll -out /home/tofol/tmp/Signed/NETStandard.dll
Succeeded
```
I would expect osslsigncode to work the same in the ps1 script as it does in the PS cli, but I can't get it to work.

**Comment by mtrojnar** [comment]
Quoting tends to be tricky in PowerShell...
This may be useful: https://slai.github.io/posts/powershell-and-external-commands-done-right/
Alternatively, you may try escaping the space with the grave-accent(`): https://ss64.com/ps/syntax-esc.html
It doesn't look like your problem is specific to osslsigncode, so I'm closing this issue.
