### ISSUE TITLE
Signing with pkcs11 backed key only (local cert)

### ISSUE THREAD

**Issue by Maximebb** [mtrojnar/osslsigncode#145]
While setting up osslsigncode to use a Google KMS backed key using their [PKCS#11 module](https://cloud.google.com/kms/docs/reference/pkcs11-library), I realized I couldn't use the pkcs11module option without also providing pkcs11cert. 

The issue is, Google KMS only supports keys and does not provide a certificate interface. We could go for an alternative, but we'd like to have an option to use pkcs11modules for keys with local certs. To illustrate what I'm referring to:
> osslsigncode sign \\
>     -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so \\
>     -pkcs11module /usr/lib64/libkmsp11/libkmsp11.so \\
>     -certs /etc/ssl/certs/test-signing.pem \\
>     -key 'pkcs11:object=ov-code-signing-hsm' \\
>     -t http://timestamp.digicert.com \\
>     -in new-binary.exe -out new-binary-signed.exe

This is currently outputting the following:
> Engine "pkcs11" set.  
> 140666295676352:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE  
> Failed`

**Comment by mtrojnar** [comment]
I agree.  https://github.com/mtrojnar/osslsigncode/blob/98308f2e0a6b625aa59a060d4bb00296ab305778/osslsigncode.c#L5206 should not be a critical error, but it should gracefully fall back to reading the certificate from file instead.

@olszomal Would you fix it?

**Comment by olszomal** [comment]
I try to reproduce this error and it works for me.

The following options can be used with the pkcs11module:
`-certs` - the signing certificate to use
`-pkcs11cert` - PKCS#11 URI identifies a certificate in the token
``` sh
./osslsigncode sign \
-pkcs11engine /usr/lib64/engines-1.1/pkcs11.so \
-pkcs11module /usr/lib64/pkcs11/opensc-pkcs11.so \
-certs certs/intermediate.pem \
-pkcs11cert 'pkcs11:token=MyePass2003%20(User%20PIN);type=cert;object=Certificate' \
-key 'pkcs11:token=MyePass2003%20(User%20PIN);type=private;object=key' \
-in unsigned.exe \
-out signed.exe 
```
I can disable the confusing error created while searching for the certificate:
```
140666295676352:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE
Failed
```
[Maximebb](https://github.com/Maximebb), is this the complete generated output?

**Comment by Maximebb** [comment]
I'm getting this as a full output:
```console
$ sudo -E osslsigncode sign \
>     -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so \
>     -pkcs11module /usr/lib64/libkmsp11/libkmsp11.so \
>     -certs /etc/ssl/cert/signing-cert.pem \
>     -key 'pkcs11:object=ov-code-signing-hsm' \
>     -t http://timestamp.digicert.com \
>     -in frontend.exe -out frontend-signed.exe
Engine "pkcs11" set.
PKCS7_dataFinal failed
Signing failed
140390590270912:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE
140390590270912:error:8207A020:PKCS#11 module:pkcs11_private_encrypt:Data invalid:p11_rsa.c:116:
Failed
```
I realize now that the PKCS7 error might be more meaningful if it works for you. I was under the impression the missing pkcs11cert option was the cause for the second one.

I do know the exact same signing-cert file is used for jsign and is validated using openssl for other Authenticode signatures. I'm not really sure what the PKCS11_dataFinal failure is really about.

**Comment by mtrojnar** [comment]
It's `PKCS7_dataFinal` (finalizing PKCS#7 signature) and not `PKCS11_dataFinal`. https://en.wikipedia.org/wiki/PKCS_7
The error says that your `/usr/lib64/libkmsp11/libkmsp11.so` module returned the `CKR_DATA_INVALID` error code.
