### ISSUE TITLE
Request: additional setup documentation for AWS Amazon Linux 2

### ISSUE THREAD

**Issue by HarmlessDave** [mtrojnar/osslsigncode#153]
Request: additional setup documentation for AWS Amazon Linux 2.  

So far I've figured out that It's necessary to run these, at least if you have not brought in "everything" using sudo yum groupinstall "Development Tools"

sudo yum install openssl-devel
sudo yum install libcurl-devel
sudo yum install gcc
sudo yum install gcc-c++
sudo yum install cmake3

cmake3 ..   -Dssl-path=/usr/ -Dcurl-path=/usr/

```
-- makecerts.sh:
/var/www/phpfiles/osslsigncode-2.3/build/Testing/certs/cert.der: No such file or directory
CMake Error at cmake/CMakeTest.cmake:37 (string):
  string sub-command SUBSTRING requires four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:49 (include)
```

**Comment by sebthom** [comment]
@HarmlessDave the build instructions in the readme are not complete. I am having difficulties building the code on Debian. Anyways, the reason for the error message `string sub-command SUBSTRING requires four arguments.` is that the `faketime` command is missing. No idea how to install it on Amazon Linux, but maybe this helps: https://command-not-found.com/faketime

**Comment by mtrojnar** [comment]
@olszomal Maybe we should check for prerequisites, such as faketime, and produce more informative errors.  What do you think?

**Comment by olszomal** [comment]
Thanks for your feedback, I'm working on it.
