### ISSUE TITLE
Osslsigncode 2.3 - Released Windows EXE won't run

### ISSUE THREAD

**Issue by Thenakedgun** [mtrojnar/osslsigncode#155]
**Problem:**

[osslsigncode_2.2_windows.zip](https://github.com/mtrojnar/osslsigncode/releases/download/2.2/osslsigncode_2.2_windows.zip) works fine when extracted, however, the subsequent version [osslsigncode-2.3_windows.zip](https://github.com/mtrojnar/osslsigncode/releases/download/2.3/osslsigncode-2.3_windows.zip) does not produce output in Powershell or Command Prompt, nor can it execute any commands that I know to work with version 2.2

I also tried it on my Windows Build Server & ran into a very similar problem. 2.2 worked fine, but 2.3 wouldn't start citing missing DLLs; after providing them, it still failed to start. 

**System:**

Windows 10 Home
Windows Server 2016

**Steps to Reproduce:**

_Windows 10 Home_
- Navigate to [the releases page](https://github.com/mtrojnar/osslsigncode/releases/tag/2.3) 
- Download & extract `osslsigncode-2.3_windows.zip` into a new directory
- Open Powershell / CMD and run: `.\osslsigncode.exe`, `.\osslsigncode.exe --help`, etc
- Nothing Happens

_Windows Server 2016_
- Repeat the above steps
- Instead of "Nothing Happens", the following error is displayed:
- "The program can't start because VCRUNTIME140D.dll is missing from your computer. Try reinstalling the program to fix this problem."
- If I provide it, it then requests UCRTBASED.dll. 
- Providing both DLLs & then trying to launch the program, it then just says, "The application was unable to start correctly (0xc000007b)."

**Guess:**

I'm pretty sure that vcruntime140d.dll is actually a debug version of the DLL. Could it be that the Windows version for 2.3 might not have been built for release?

**Comment by mzros** [comment]
Version 2.3 is running fine on Windows 11 here.

But I still cannot get it running within my docker container 'mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022'
it always returns exit code -1073741515

**Comment by mtrojnar** [comment]
Can you please try using the CI build from https://github.com/mtrojnar/osslsigncode/actions/runs/2740421594#artifacts?

**Comment by mtrojnar** [comment]
I'm asking because I'd like to make sure this issue is fixed before the next release planned in a few days.

**Comment by Thenakedgun** [comment]
Looks good on my end. Running v2.4-dev in the Win10 Home command line, I get the output as expected, can check the version, etc. Tried signing my most recent MSI & it worked as expected & produced the same output file as v2.2. Repeated tests on Win Server 2016 as well & it worked there too. 

Thanks a lot for that! This tool saved me from pulling all of my hair out after hours of failing to get signtool.exe to work with some file formats my company was pigeon-holed into using.

**Comment by mtrojnar** [comment]
@Thenakedgun Thank you for your feedback.

@mzros Does the latest build fix it for you?
