### ISSUE TITLE
Can't run under Wine on macOS

### ISSUE THREAD

**Issue by MarshalX** [mtrojnar/osslsigncode#172]
**Env**
Mac Air M1. I tried the latest release for Apple Silicon from brew (2.3). I use `wine-crossover` from `gcenx/wine` (brew)

**Reproduce**
```bash
wine cmd /c start /wait /unix ./osslsigncode
```

**Actual** 
```
050c:fixme:exec:SHELL_execute flags ignored: 0x00000100
```

**Expected**
osslsigncode will work fine

**Notes**
osslsigncode works fine without Wine `./osslsigncode` . But it's not [my goal](https://github.com/dustinblackman/mono-signtool)

**Comment by mtrojnar** [comment]
Shouldn't you rather use osslsigncode.exe (from https://github.com/mtrojnar/osslsigncode/releases/download/2.4/osslsigncode-2.4-x64-windows-static.zip) with wine?

**Comment by MarshalX** [comment]
> Shouldn't you rather use osslsigncode.exe (from https://github.com/mtrojnar/osslsigncode/releases/download/2.4/osslsigncode-2.4-x64-windows-static.zip) with wine?

It works) thank you!
