### ISSUE TITLE
Legacy pkcs12 ciphers support

### ISSUE THREAD

**Issue by fdelapena** [mtrojnar/osslsigncode#178]
With recent openssl, there are pkcs12 files not supported, despite they are still being generated on some operating systems with long time obsolete ciphers. It is known the `-legacy` openssl argument helps with this even with OpenSSL 3, so libssl should have some feature to support them from code:

```
Failed to parse PKCS#12 file: example.p12 (Wrong password?)
404898CA067F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

**Comment by mtrojnar** [comment]
Using the legacy provider for decoding pkcs12 files with OpenSSL 3.0 is a good idea.

**Comment by stweil** [comment]
There is a [related Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024434).
