### ISSUE TITLE
Error: Failed to set 'dynamic' engine

### ISSUE THREAD

**Issue by knzivid** [mtrojnar/osslsigncode#180]
First of all, thank you for your contributions to this tool. I am upgrading from 2.1 to the latest version and I think I hit a bug. All of my dependencies are from Ubuntu 20.04. osslsigncode version 2.4 works but version 2.5 does not, with the following error.

```
bad engine id
Failed to set 'dynamic' engine
139681881966976:error:260B606D:engine routines:dynamic_load:init failed:../crypto/engine/eng_dyn.c:487:
Failed
```

I think the offending commit is b8d83bb15e4364b169920d1cf262ac8475673d27

```diff
-			|| !ENGINE_ctrl_cmd_string(engine, "ID", "pkcs11", 0)
+			|| !ENGINE_ctrl_cmd_string(engine, "ID",
+				options->p11engine ? options->p11engine : "pkcs11", 0)
```

I pass `-pkcs11engine /path/to/pkcs11.so` to osslsigncode. That would mean `ENGINE_ctrl_cmd_string` would receive the full path instead of just `pkcs11` as before. Reverting this commit made osslsigncode work again.

My CMake build configuration

```
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
-- Using bash completions dir /usr/local/share/bash-completion/completions
-- Looking for getpass
-- Looking for getpass - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for mmap
-- Looking for mmap - found
-- cURL support enabled
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- makecerts.sh failed
-- faketime not found in $PATH, please install faketime package
-- Configuring done
-- Generating done
```

**Comment by mtrojnar** [comment]
I indeed didn't think about full path being used for the engine.
Couldn't you simply put the engine in the designated directory and select it by name?

**Comment by btn-paragon** [comment]
I hit this problem yesterday and reverting the referenced commit works for me (thanks @knzivid ). 

The main readme for the project shows using the full path to the engine in the examples
https://github.com/mtrojnar/osslsigncode/blob/b8cb44fa47440e7bc294a323af41550c8f08f27d/README.md?plain=1#L137

seems like changing this would affect a lot of people.

**Comment by alexkowel** [comment]
It appears Fedora 35-38 users also got affected by this issue (including myself), because 2.5 accidentally appeared in the repos as a "minor" update. See here https://src.fedoraproject.org/rpms/osslsigncode.

**Comment by knzivid** [comment]
Thank you for the fix :)

**Comment by Patazerty** [comment]
I think I still have this bug on latest commit (at the time of writing) [7bb21c35396b8130cdd4e9a52e391d9f8d21908f  ](https://github.com/mtrojnar/osslsigncode/commit/7bb21c35396b8130cdd4e9a52e391d9f8d21908f) , reverting to 2.4 "fixes" the issue.

From my advanced print-based debugging I can say that is the `ENGINE_ctrl_cmd_string(engine, "LOAD", NULL, 0)` call that fails. Let me know if there's anything I can do to further debug this
