### ISSUE TITLE
Signing with GlobalSign

### ISSUE THREAD

**Issue by franchb** [mtrojnar/osslsigncode#190]
Hi!

I'm trying to sign Windows binary using GlobalSign Extended Validation (EV) Code Signing Certificates hardware USB token [https://shop.globalsign.com/en/code-signing](https://shop.globalsign.com/en/code-signing).

I use Fedora 36 and GlobalSign RPM package from [wget https://www.globalsign.com/en/safenet-drivers/USB/10.7/Safenet_Linux_Installer_RPM_x64.zip](https://www.globalsign.com/en/safenet-drivers/USB/10.7/Safenet_Linux_Installer_RPM_x64.zip).

After compiling latest `osslsigncode` binary I run it using command:

```shell
osslsigncode sign \
    -pkcs11engine /usr/lib64/p11-kit-proxy.so \
    -pkcs11module /usr/lib64/libeToken.so \
    -pkcs11cert 'pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust;object=cert' \
    -key 'pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust;object=key' \
    -in windows-app.exe -out windows-app-signed.exe
```

The error output is:

```shell
Failed to set 'dynamic' engine
40F82700127F0000:error:1280006A:DSO support routines:dlfcn_bind_func:could not bind to the requested symbol name:crypto/dso/dso_dlfcn.c:188:symname(bind_engine): /usr/lib64/p11-kit-proxy.so: undefined symbol: bind_engine
40F82700127F0000:error:1280006A:DSO support routines:DSO_bind_func:could not bind to the requested symbol name:crypto/dso/dso_lib.c:176:
40F82700127F0000:error:13000068:engine routines:dynamic_load:DSO failure:crypto/engine/eng_dyn.c:455:
Failed
```

Does anybody knows where can I find some information on selecting correct values for `osslsigncode` arguments in such case?

Thank you!

**Comment by mtrojnar** [comment]
The error message is correct. p11-kit-proxy.so is not an OpenSSL engine. Install the pkcs11 engine and allow osslsigncode to select it automatically.
