### ISSUE TITLE
Unable to Load Module

### ISSUE THREAD

**Issue by salih-okur** [mtrojnar/osslsigncode#191]
Hi,
I am trying to sign with smartcard using osslsigncode. The smartcard I use has its own library(libakisp11.so). When I give the path to that library in pkcs11module, it gives unable to load module error. Can you help me?

My Code:
sslsigncode sign -certs 1.cer -pkcs11engine /usr/lib/x86_64-linux-gnu/engines-3/libpkcs11.so -pkcs11module /home/akis/libakisp11.so -in app.exe -out signedapp.exe

Error:
Engine "pkcs11" set.
Unable to load module /home/akis/libakisp11.so
Unable to load module /home/akis/libakisp11.so
PKCS11_get_private_key returned NULL
Failed to load private key (null)
008E959BAD7F0000:error:41000007:PKCS#11 module:ERR_CKR_error:Invalid arguments:p11_load.c:92:
008E959BAD7F0000:error:13000080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:79:
Failed

**Comment by mtrojnar** [comment]
What does `file /home/akis/libakisp11.so` print?

**Comment by salih-okur** [comment]
This is my library module path

**Comment by mtrojnar** [comment]
Are you sure that `file /home/akis/libakisp11.so` prints `This is my library module path` on your system?  Which version of `file` command do you use?

**Comment by salih-okur** [comment]
Ohh ı misunderstand the question.File /home/akis/libakisp11.so cannot print anything it is used to interact with card

**Comment by olszomal** [comment]
You can use `pkcs11-tool` to load the `libakisp11.so` module and check your private key:
```
$ pkcs11-tool --module /usr/lib64/pkcs11/libsofthsm2.so --login --list-objects
Using slot 0 with a present token (0x7124eacf)
Logging in to "MyToken".
Please enter User PIN: 
Private Key Object; RSA 
  label:      key
  ID:         f172884fb0dcd81a
  Usage:      decrypt, sign, unwrap
  Access:     none
Public Key Object; RSA 2048 bits
  label:      key
  ID:         f172884fb0dcd81a
  Usage:      encrypt, verify, wrap
  Access:     none
```
