### ISSUE TITLE
File handle of input file not closed

### ISSUE THREAD

**Issue by egreathou** [mtrojnar/osslsigncode#198]
I am compiling osslsigncode as a .lib instead of .exe for use within a .Net CLR C++ Dll. The input file to be signed is opened with the map_file function. CreateFile sets the local fhandle variable, but the handle is not closed until signcode_main exits. This appears to be by-design but would it be possible to also close the file handle after the input file is unmapped?

**Comment by mtrojnar** [comment]
A side question: Do you intend to distribute our .Net CLR C++ DLL?  If so, how can I get a copy of your DLL's source code?  Bear in mind the code is licensed on GPL 3.0 and your DLL is a derived work.

**Comment by egreathou** [comment]
Hi Michal,

We decided to take a different route and won't be using your code at this
time. In our previous plans, we were not going to be redistributing it but
rather, using it for a backend process on our servers. The servers would be
used by our customers though, through interaction with our web UI. If you
could help me determine if that usage is covered by the license then we
will be sure to take that into consideration if our plans change in
the future. Thank you for reaching out to me to let me know.

-Eric

**Comment by mtrojnar** [comment]
@egreathou Thank you for the explanation.  I case you change you mind, GPL indeed does not restrict the way you use the software, including customer-facing services.
