### ISSUE TITLE
Failed to parse PKCS#12 file: p12key.p12 (Wrong password?)

### ISSUE THREAD

**Issue by axi92** [mtrojnar/osslsigncode#199]
I use this, the password is replaced with one that looks like that:

`osslsigncode sign -pkcs12 p12key.p12 -pass 41892061-2B79-4ACA-955F-9F283EF583F9 -i https://www.domain.com/ -t http://timestamp.digicert.com -in test.exe -out test.exe.signed`

I get this error:
```
Failed to parse PKCS#12 file: p12key.p12 (Wrong password?)
005E209B5A7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Failed
```

Version:
```
osslsigncode 2.5, using:
	OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
```

Is there anything I did wrong?
I can open the pkcs12 file with the keytool so the password is correct.

Edit: I just read it has to do something with a legacy format? Can I convert that to the new up to date format?

**Comment by axi92** [comment]
I was able to convert it with this help: https://kb.globalscape.com/Knowledgebase/11040/Converting-an-Incompatible-PKCS12-Format-File-to-a-Compatible-PKCS12

**Comment by nwithan8** [comment]
Out of curiosity, @axi92 , which cipher did you switch to? I'm running into the same issue as looking to change the cipher to something non-legacy

**Comment by axi92** [comment]
@nwithan8 
I don't have the old legacy keystore anymore. But I just opened our working one:

I am using KeystoreExplorer way more easy to work with keys and keystores =)
Just checked the properties:

```
Keystore:
    Type: PKCS12
    Provider: SUN
            Private Key
                Algorithm: RSA
                Key Size: 4096 bits
                Format: PKCS#8
                    Public Key
                        Algorithm: RSA
                        Key Size: 4096 bits
                        Format: X.509
                    Signature Algorithm: SHA-256 with RSA
```
And I also imported the complete certificate chain from digicert. We only got the CSR back with our cert but not the whole chain. I had to manually search for the right Digicert Root cert to import it into the keystore so the validation works everywhere.

I hope this helps.
