### ISSUE TITLE
Dependency on openssl1.0, not working on Amazon Linux 2022

### ISSUE THREAD

**Issue by xuy98** [mtrojnar/osslsigncode#200]
osslsigncode depends on openssl1. Now Amazon Linux 2022 has openssl3 installed. Is there any plan for osslsigncode to move to openssl3?

**Comment by olszomal** [comment]
You can configure and build the osslsigncode project with any openssl and suitable curl
[https://github.com/mtrojnar/osslsigncode#building](https://github.com/mtrojnar/osslsigncode#building)
```
$ mkdir build && cd build && cmake -S .. -DCMAKE_PREFIX_PATH="/opt/openssl-3.0.7;/opt/curl-7.86"
$ cmake --build .
$ ./osslsigncode --version
osslsigncode 2.5, using:
	OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
	libcurl/7.86.0 OpenSSL/3.0.7
```
