### ISSUE TITLE
Trouble with run after bad install osslsigncode

### ISSUE THREAD

**Issue by AlexanderVerner** [mtrojnar/osslsigncode#204]
Hello!
I follow [this guide](https://www.electron.build/tutorials/code-signing-windows-apps-on-unix#signing-windows-app-on-mac-using-osslsigncode), when trying sign bynary file with GlobalSign token on mac for windows-platform and take silly error:

`iMac-1234:~ runner$ osslsigncode -h`
`-bash:  /usr/local/bin/osslsigncode: Permission denied`

If try with sudo-prefix:

`iMac-1234:~ runner$ sudo osslsigncode -h`
`Password:`
`sudo: osslsigncode: command not found`

I going to directory with osslsigncode-file, where was drop file from release tarball [osslsigncode-2.5-macOS.zip](https://github.com/mtrojnar/osslsigncode/releases/download/2.5/osslsigncode-2.5-macOS.zip) and run `ls -l ` for viewing, how is permissions for this file:

`iMac-1234:bin runner$ ls -l /usr/local/mac-dev/bin`
`total 9752`
`-rwxr-xr-x  1 runner  wheel     6709 29 dec 18:50 c_rehash`
`-rwxr-xr-x  1 runner  wheel   680440 29 dec 18:50 openssl`
`-rw-rw-r--@ 2 runner  staff  4299344 12 aug 20:12 osslsigncode`

I have a symlink for this file in /usr/local/bin 

`...`
`lrwxr-xr-x  1 runner  admin    35 11 jan 18:16 osslsigncode -> /usr/local/mac-dev/bin/osslsigncode`
`lrwxr-xr-x  1 runner  admin    33 11 jan 12:33 pinky -> ../Cellar/coreutils/9.1/bin/pinky`
`...`

I suspect it's because I installed osslsigncode incorrectly. I download tarball, it unpacked and drop all content from directory in /usr/local/mac-dev/. Then I set file permissions to the current user `sudo chown $USER osslsigncode` and try run this.

How correctly install from tarball [osslsigncode-2.5-macOS.zip](https://github.com/mtrojnar/osslsigncode/releases/download/2.5/osslsigncode-2.5-macOS.zip)? Sorry for my silly question :)

**Comment by mtrojnar** [comment]
Your osslsigncode binary is not executable:
```sh
-rw-rw-r--@ 2 runner  staff  4299344 12 aug 20:12 osslsigncode
```
You need to update the file permissions:
```sh
$ sudo chmod a+x /usr/local/mac-dev/bin/osslsigncode
```

**Comment by AlexanderVerner** [comment]
Thx, I understand that it is not executable, but how to get executable? Perform some build?

**Comment by mtrojnar** [comment]
> how to get executable?

I believe I already answered this question.
```sh
$ sudo chmod a+x /usr/local/mac-dev/bin/osslsigncode
```

**Comment by AlexanderVerner** [comment]
Oh sorry, i thinked what is a partial answer this question. I will try your solution today and return with report about successes :)

**Comment by AlexanderVerner** [comment]
All right! Thx so much
