### ISSUE TITLE
Distribute official binaries for osslsigncode

### ISSUE THREAD

**Issue by Calinou** [mtrojnar/osslsigncode#22]
It would be easier to use osslsigncode if official binaries were available on the Releases tab. These could be built and uploaded automatically on each release using Travis CI or similar.

While distributing portable Windows and macOS binaries should be relatively easy, it may be more challenging to provide portable Linux binaries. Maybe this could be achieved using [Holy Build Box](http://phusion.github.io/holy-build-box/) (I haven't tested it yet).

This would make it easier to integrate osslsigncode in CI workflows (see https://github.com/godotengine/godot/pull/32556).

**Comment by mtrojnar** [comment]
osslsigncode has the following dependencies:
 - libcrypto: https://www.openssl.org/source/license.html
 - libcurl: https://curl.haxx.se/docs/copyright.html
 - libgsf: https://github.com/GNOME/libgsf/blob/master/COPYING.LIB

libgsf uses LGPL, which makes any statically linked code a derived work.

We could make fairly portable static builds if we disabled libgsf support.  What do you think?

**Comment by Calinou** [comment]
I believe it shouldn't be a problem to link libgsf statically, as osslsigncode is under a GPL-compatible license. (This means it can be used under GPL conditions legally.)

Which features become unavailable when libgsf is disabled?

**Comment by mtrojnar** [comment]
MSI file format support is built on top of libgsf.

**Comment by Calinou** [comment]
@mtrojnar That'd be sufficient for our use cases, as we don't provide MSI installers :slightly_smiling_face:

**Comment by mtrojnar** [comment]
@Calinou Would you like to submit a PR or to possibly sponsor our work on this feature?

**Comment by Calinou** [comment]
@mtrojnar I'll try to look into it in January.

**Comment by mtrojnar** [comment]
@olszomal has started working on this issue.

**Comment by ebourg** [comment]
Regarding the Linux binaries, note that osslsigncode is already packaged for [Debian](https://tracker.debian.org/pkg/osslsigncode), [Ubuntu](https://packages.ubuntu.com/focal/osslsigncode) and [openSUSE](https://build.opensuse.org/package/show/openSUSE%3AFactory/osslsigncode). There was also a [Fedora](https://src.fedoraproject.org/rpms/osslsigncode) package but it seems to be dead now.

**Comment by mtrojnar** [comment]
Done: https://github.com/mtrojnar/osslsigncode/releases/tag/2.1
