### ISSUE TITLE
Publish official docker image

### ISSUE THREAD

**Issue by Sytten** [mtrojnar/osslsigncode#233]
Hi there!
Could it be possible to publish a docker image similar to https://github.com/giantswarm/signcode-util/blob/main/Dockerfile to Dockerhub or something similar. Since there are no official ubuntu builds and the PPA for ubuntu 20.04 is REALLY outdated, it would be a great alternative for people like myself looking for a simple way to integrate the tool in a CI pipeline.
Thanks

**Comment by mtrojnar** [comment]
Does https://hub.docker.com/r/trojnara/osslsigncode work for you?

**Comment by Sytten** [comment]
Good first step, thanks for that!
A few suggestions:
- Create a tag for each version instead of just latest, that way people can pin their version (usually I create a github action on releases released)
- Add the Dockerfile that was used to build the image somewhere in this repository (I might have suggestions for it once I see it)
- Add a readme (overview) to the dockerhub repository
- Link to the github repository directly as source instead of the current link in the description

**Comment by mtrojnar** [comment]
* Take a look at the source: https://github.com/mtrojnar/osslsigncode/blob/master/Dockerfile
* Yes, I'm going to tag releases after I publish the next release.
* How to "link to the github repository directly as source"?  I have very little experience with Docker and Docker Hub.
* Would you like to contribute a README?

**Comment by mtrojnar** [comment]
@Sytten I pushed the v2.8 tag.  Which of your repositories should I use to as a template for automating the process?
