### ISSUE TITLE
Question: CAB File Signature Specification 

### ISSUE THREAD

**Issue by trykacz** [mtrojnar/osslsigncode#238]
Hello,

I have a quick questions which i hope you can answer:

Context:
I have a problem understanding the MS Authenticode Signature of CAB files.

I found the Specification of the MS Authenticode signature for PE files, but as far as i understand CAB files are no PE files.
Moreover, I understand the concept of CAB files and I understand their format.

Technically i think i understand what is happening when a digital signature is created with your tool.
As far as I understand, the digest is computed and a PKCS#7 signature is created, which is appended to the CAB file.
The CAB Header needs to be adapted to contain the 'abReserve' header which contains information about the signauture.

Question:
But I dont really understand WHY this is happening. Where is this specified? Where does this information come from?
Is this only reverse engineered from "officialy" signed CAB files? Is this written somewhere?

**Comment by olszomal** [comment]
Documentation:
[Microsoft Cabinet Format](https://learn.microsoft.com/en-us/previous-versions/bb417343(v=msdn.10))

**Comment by trykacz** [comment]
As i mentioned, i understand the CAB Format. But even in the link you shared the modifications which are done with the Header are Not specified. 

E.g.: where is specified which parts are used to compute the digest for the CAB file?

**Comment by mtrojnar** [comment]
This is all the documentation we had for developing the code.  It's indeed far from perfect, and @olszomal often had to guess the details.  So, [Use the Source, Luke](https://encyclopedia2.thefreedictionary.com/Use+the+Source+Luke): https://github.com/mtrojnar/osslsigncode/blob/master/cab.c
