### ISSUE TITLE
Can't use process substitution with `-certs`

### ISSUE THREAD

**Issue by r1b** [mtrojnar/osslsigncode#24]
I store my cert & key in a cloud service - at signing time I pull them down and attempt to use with process substitution like this:

```bash
osslsigncode sign -certs <( get-the-cert ) -key <( get-the-key ) ...
```

`osslsigncode` complains:

> Failed to read certificate file: /dev/fd/$N

I believe this is because `read_certs_with_pass` seeks to the beginning of the file [1] [2]. But this seems silly, why do we need to `seek(0)` immediately after we read the file? Am I missing something?

[1] https://github.com/mtrojnar/osslsigncode/blob/2ffa5a9d69842f9b52ce30cb98aedb6e672b827b/osslsigncode.c#L2252-L2264
[2] https://en.wikipedia.org/wiki/Process_substitution#Limitations

**Comment by r1b** [comment]
Hm I see, this is because we read a PKCS7 copy of the cert with `d2i_PKCS7_bio` before we store the x509 cert - too bad!

**Comment by mtrojnar** [comment]
Yes, this tool  indeed needs seekable files, and not just streams of data.

**Comment by r1b** [comment]
Certainly it needs seekable files to e.g write the signature but not necessarily to read the cert and key. At any rate, I see that I can get what I want by providing a PKCS12 file [1] which does not require a seek. I am happy now.

[1] https://github.com/mtrojnar/osslsigncode/blob/2ffa5a9d69842f9b52ce30cb98aedb6e672b827b/osslsigncode.c#L2659-L2666
