### ISSUE TITLE
Improve readme to build on linux

### ISSUE THREAD

**Issue by axi92** [mtrojnar/osslsigncode#242]
Hi I used the older version 2.1.0 and was able to build it with this in my dockerfile:
```
RUN apt update && apt install -y -qq --no-install-recommends build-essential pkg-config libssl-dev libcurl4-openssl-dev wget cmake && \
  wget --no-check-certificate https://github.com/mtrojnar/osslsigncode/releases/download/2.5/osslsigncode-2.5.tar.gz && \
  tar -xf osslsigncode-*.tar.gz && \
  rm *.tar.gz && \
  cd osslsigncode* && \
  ./configure && make && make install
  ```
  
According to the README.md I need to:
- Navigate to the build directory and run CMake to configure the osslsigncode project and generate a native build system:
```
mkdir build && cd build && cmake -S ..
```
with specific compile options:
```
  -DCMAKE_BUILD_TYPE=Debug
  -DCMAKE_C_COMPILER=clang
  -DCMAKE_PREFIX_PATH=[openssl directory];[curl directory]
  -DCMAKE_INSTALL_PREFIX=[installation directory]
  -DBASH_COMPLETION_USER_DIR=[bash completion installation directory]
```

When I download the tar.gz there is no "build" directory in that tar. Then I create the folder with `mkdir build` and `cd build` into that empty folder.
Then I dont know what I need for the cmake -S <options> command.
I tried this:
```
cmake -S=../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang 
```
With that output:
```
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:12 (project):
  The CMAKE_C_COMPILER:

    clang

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/osslsigncode-2.5/build/CMakeFiles/CMakeOutput.log".
See also "/osslsigncode-2.5/build/CMakeFiles/CMakeError.log".
```

Next I installed `apt install --no-install-recommends clang-15`

Tried the build again:
`cmake -S=../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-15`
and build
`cmake --build .`

Then I got a working binary =)

**Comment by axi92** [comment]
If somebody needs it for a Dockerfile you can use that code as a build stage:

```
FROM ubuntu:22.04 AS builder

ARG OSSLSIGNCODE_VERSION=2.5

RUN apt update && apt install -y -qq --no-install-recommends build-essential pkg-config libssl-dev libcurl4-openssl-dev clang-15 wget cmake && \
  wget --no-check-certificate https://github.com/mtrojnar/osslsigncode/releases/download/${OSSLSIGNCODE_VERSION}/osslsigncode-${OSSLSIGNCODE_VERSION}.tar.gz && \
  tar -xf osslsigncode-${OSSLSIGNCODE_VERSION}.tar.gz && \
  rm *.tar.gz && \
  cd osslsigncode-${OSSLSIGNCODE_VERSION} && \
  mkdir build && cd build && cmake -S=../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-15 && \
  cmake --build . && \
  cp /osslsigncode-${OSSLSIGNCODE_VERSION}/build/osslsigncode /osslsigncode
```
And copy it later into your image when you need it:
`COPY --from=builder /osslsigncode /usr/local/bin/osslsigncode`

**Comment by axi92** [comment]
My bad I don't work often with C or C++.
I took clang because I followed the readme: https://github.com/mtrojnar/osslsigncode/blob/44a6768089404762e8db21b75264347065203ff6/README.md?plain=1#L60

**Comment by mtrojnar** [comment]
Good point!  It's indeed not clear that those are examples of configurable build parameters, and not the required build parameters.
@olszomal could you fix it?

**Comment by marcoamendola** [comment]
> If somebody needs it for a Dockerfile you can use that code as a build stage:

Thanks @axi92 for this very elegant solution. 
I just want to add, for anybody using this approach, that it didn't work at first on my setup.
I had to install `python3-dev` package in addition to those you included.
The involved line in my Dockerfile is now:
```
RUN apt update && apt install -y -qq --no-install-recommends build-essential pkg-config libssl-dev libcurl4-openssl-dev clang-15 python3-dev wget cmake sudo
```
