### ISSUE TITLE
Failing to sign .msi file - DIFAT sectors are not supported

### ISSUE THREAD

**Issue by nneul** [mtrojnar/osslsigncode#244]
This is not occuring with a 2.0 build on ubuntu20, but does occur with fresh build of latest sources. 

Is this something particular about the msi content? It doesn't seem to affect all binaries, but is affecting the one I am trying to sign, which is a large installer (~1.3GB).

**Comment by mtrojnar** [comment]
In osslsigncode 2.2, we switched MSI implementation from libgsf, which was unsuitable for signature verification and only partially suitable for signing, to our own implementation.  This new implementation still lacks DIFAT support.

Would you like to sponsor implementing this feature to get it faster?

**Comment by max619** [comment]
@mtrojnar is there any publicly available documentation on how DIFAT sectors outside of a MSI header are handled?

I might be able to add support for that feature myself, but I can't really find any information about it.

**Comment by ebourg** [comment]
DIFAT sectors are documented in the [Compound File Binary specification](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/0afa4e43-b18f-432a-9917-4f276eca7a73). Without DIFAT sectors the maximum file size supported is either 6.875 MB with 512 bytes sectors, or 55 MB with 4096 bytes sectors.
