### ISSUE TITLE
Missing OpenSSL legacy provider on Microsoft Windows

### ISSUE THREAD

**Issue by yujiny97** [mtrojnar/osslsigncode#259]
I tried to sign at window, so i used mingw64 to make .exe file.
I made .exe file with this command line
```
gcc *.c -o osslsigncode_new.exe   
-lcrypto -lssl -lcurl \  
    -D 'PACKAGE_STRING="osslsigncode 2.4"' \  
    -D 'PACKAGE_BUGREPORT="email"' \  
    -D ENABLE_CURL  
```
then digital sign for every file types are not working anymore..
when I sign it, the messages are like this
```
Unable to load provider: legacy  
Warning: Legacy mode disabled  
```

but previous version worked well.
did I made .exe file in a wrong way..?

**Comment by mtrojnar** [comment]
Your .exe file is fine, but your OpenSSL is not properly installed.
A similar problem: https://github.com/php/php-src/issues/9890
