### ISSUE TITLE
Homebrew macOS osslsigncode fails with "dyld: Library not loaded"

### ISSUE THREAD

**Issue by rfay** [mtrojnar/osslsigncode#26]
First, congratulations on getting this project (instead of abandoned one) into homebrew.

But...

osslsigncode with latest homebrew fails every way I've tried on mojave or catalina with this message. (It seems to work on Catalina).

```
dyld: Library not loaded: /usr/local/opt/libgsf/lib/libgsf-1.114.dylib
  Referenced from: /usr/local/bin/osslsigncode
  Reason: image not found
```

homebrew info:

```
Distillers-Mac-4:ddev distiller$ brew info libgsf
libgsf: stable 1.14.46 (bottled), HEAD
I/O abstraction library for dealing with structured file formats
https://developer.gnome.org/gsf/
/usr/local/Cellar/libgsf/1.14.46_1 (153 files, 2.3MB) *
  Poured from bottle on 2020-01-02 at 09:10:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgsf.rb
==> Dependencies
Build: intltool ✘, pkg-config ✘
Required: gettext ✔, glib ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1,313 (30 days), 4,030 (90 days), 20,620 (365 days)
install-on-request: 47 (30 days), 210 (90 days), 1,133 (365 days)
build-error: 0 (30 days)
Distillers-Mac-4:ddev distiller$ brew info osslsigncode
osslsigncode: stable 2.0 (bottled)
OpenSSL based Authenticode signing for PE/MSI/Java CAB files
https://github.com/mtrojnar/osslsigncode
/usr/local/Cellar/osslsigncode/2.0_1 (8 files, 125.6KB) *
  Poured from bottle on 2020-01-02 at 09:10:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/osslsigncode.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✘, pkg-config ✘
Required: libgsf ✔, openssl@1.1 ✔
==> Analytics
install: 91 (30 days), 314 (90 days), 728 (365 days)
install-on-request: 86 (30 days), 304 (90 days), 707 (365 days)
build-error: 0 (30 days)
```

osslsigncode is osslsigncode-2.0_1.mojave.bottle.tar.gz here

Note that the suggestions in https://stackoverflow.com/questions/44125147/dyld-library-not-loaded-usr-local-opt-openssl-lib-libcrypto-1-0-0-dylib and https://blog.junjizhi.com/all/2019/12/17/git-fetch-libssl-error.html didn't get me working.

**Comment by rfay** [comment]
I confirm that by moving my CI test runner to Catalina I'm able to work around this. So Catalina definitely works, Mojave is definitely broken.

**Comment by rfay** [comment]
Edited: I can get it to work on one Catalina machine but not on one that's brew-installed from scratch. Changed title.

**Comment by rfay** [comment]
I think I'm able to fix this with `brew link libgsf glib pcre`, I guess those aren't linked by default?

**Comment by olszomal** [comment]
It looks like a package dependency problem.
The bug does not occur when compiling from the master branch sources.
````
$ ./osslsigncode -v
osslsigncode 2.1.0, using:
    OpenSSL 1.1.1d FIPS  10 Sep 2019
    libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.2/openssl/zlib nghttp2/1.39.2
    no libgsf available
````
I'd suggest you to report this bug to the package maintainer and close this issue.

**Comment by rfay** [comment]
Do you have any idea who the package maintainer is? I assumed that since osslsigncode just got moved from the old obsolete repo to this one that @mtrojnar had accomplished that!  It was just changed from sourceforge to this repo in https://github.com/Homebrew/homebrew-core/commit/56c2a82222199f356cc642b8e6b21e4976aada4f

**Comment by mtrojnar** [comment]
> Do you have any idea who the package maintainer is? I assumed that since osslsigncode just got moved from the old obsolete repo to this one that @mtrojnar had accomplished that! It was just changed from sourceforge to this repo in [Homebrew/homebrew-core@56c2a82](https://github.com/Homebrew/homebrew-core/commit/56c2a82222199f356cc642b8e6b21e4976aada4f)

@olszomal meant the Homebrew package maintainer, and not the upstream package maintainer (me).

The commit you just referer to is signed-off by @fxcoudert.  Either this person is the maintainer of the Homebrew package, or knows the maintainer.

**Comment by rfay** [comment]
This recently popped up again, `brew upgrade osslsigncode libgsf glib pcre` resolved it.
