### ISSUE TITLE
No verbose output when verify fails

### ISSUE THREAD

**Issue by sztomi** [mtrojnar/osslsigncode#272]
I have an issue verifying signatures after signing a binary with osslsigncode, but only when I'm running it in docker. The image I'm using is based on ubuntu:22.04, and seems to to contain the same set of certs in `/etc/ssl/certs` and `/usr/share/ca-certificates/mozilla` as my host OS (which is 22.10). 

I get the following output when running `osslsigncode verify -verbose <binary>`:

```
Use the "-CAfile" option to add one or more trusted CA certificates to verify the signature.
Failed
```

I was hoping `-verbose` would let me gain some insight into why the existing certs are not used in this case. I do get a lot more verbose output when it succeeds. Any idea what might be wrong? I understand that I could pass the entire trust chain with -CAfile arguments, but that's not very ergonomic and I would prefer to use the system certs when verifying. 

```
❯ osslsigncode --version
osslsigncode 2.5, using:
        OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.8 7 Feb 2023)
        libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.52.0 librtmp/2.3
```

(this is the version in the container; the host version is 2.2).

**Comment by mtrojnar** [comment]
Please try osslsigncode 2.6.

**Comment by sztomi** [comment]
I can confirm that upgrading to 2.6 fixes the issue. Thanks!
