### ISSUE TITLE
Dump .cat files list

### ISSUE THREAD

**Issue by rul3rst4** [mtrojnar/osslsigncode#274]
Hi, I've implemented a way to get a list of files that the catalog have, with the filename and hash of each file.
I've implemented this by refactoring the actual verification chain of the catalog file, that checks wether the catalog file have a file hash in it's catalog.

Will that be any useful for this project? If so, I can clean up the code and make a PR. I've made this to automate the process of verifying a windows driver signature and it's dependencies files that are in the catalog file.

**Comment by mtrojnar** [comment]
Could you elaborate on why you think that this feature may be useful?
