### ISSUE TITLE
appx signing failed

### ISSUE THREAD

**Issue by karlvr** [mtrojnar/osslsigncode#318]
I am trying to debug a failed signing of my `.appx` package. It is quite a large package, approximately 70MB. After signing, which completes successfully, Windows rejects the package with an "Error in parsing the app package." error message in the App Installer window (and a "Cannot open app package" heading).

I am not sure how to usefully debug this issue... I have renamed the `.appx` file to a `.zip` and tried to extract it and that fails, whereas unzipping an unsigned `.appx` is successful so I think the zip has been corrupted by the signing process.

```
file #1:  bad zipfile offset (local header sig):  72780927
file #2:  bad zipfile offset (local header sig):  72779657
file #3:  bad zipfile offset (local header sig):  66912754
file #4:  bad zipfile offset (local header sig):  66554130
file #5:  bad zipfile offset (local header sig):  66910243
file #6:  bad zipfile offset (local header sig):  66742882
file #7:  bad zipfile offset (local header sig):  66884290
file #8:  bad zipfile offset (local header sig):  66793242
file #9:  bad zipfile offset (local header sig):  66880079
...
```

@panekmaciej if you're interested, I can provide some test files, otherwise I will try digging into the code to see if I can work anything out.

**Comment by karlvr** [comment]
Further investigation reveals that [jsign](https://github.com/ebourg/jsign) v5.1 (built from HEAD) does successfully sign my `.appx`...

**Comment by mtrojnar** [comment]
We have no way to fix this issue without a way to reproduce it.
