### ISSUE TITLE
configure: error: OpenSSL 1.1.0 or later is required. https://www.openssl.org/

### ISSUE THREAD

**Issue by free-andy** [mtrojnar/osslsigncode#33]
我在 centos 7 上出现了这样的错误，但是我 openssl version 已经更新到了 `1.1.1`

![image](https://user-images.githubusercontent.com/32917637/75001248-caf5ec80-549b-11ea-87fe-6ba64067b13d.png)

**Comment by mtrojnar** [comment]
You normally need `yum install openssl-devel` on CentOS.
In case your OpenSSL is installed in a non-standard way, you need to make sure your `pkg-config` is configured to find OpenSSL's `libcrypto.pc`.

**Comment by free-andy** [comment]
要得
