### ISSUE TITLE
Can osslsigncode work with pkcs11 on Yubikey HSM 2?

### ISSUE THREAD

**Issue by axi92** [mtrojnar/osslsigncode#332]
Because of the 2023 changes in code signing where you have to store your cert we like to move to the Yubikey HSM 2 that supports pkcs11 also over network.
https://developers.yubico.com/yubihsm-shell/yubihsm-pkcs11.html

Does osslsigncode support this?
Any hints on how to use it in that setup?

**Comment by mtrojnar** [comment]
Yes, osslsigncode supports PKCS#11, and you can find hints for using a PKCS#11 module in https://github.com/mtrojnar/osslsigncode/blob/master/README.md
