### ISSUE TITLE
Osslsigncode to use keys/Cert from HSM

### ISSUE THREAD

**Issue by AamirZahid** [mtrojnar/osslsigncode#34]
Hello Experts,

I am new in the community, I was looking if there is a way to integrate osslsigncode to pick keys from HSM which are based on pkcs11 standard?
I have a working installation of OpenSSL which can successfully generate/use keys from HSM using -engine switch, any help would be really appreciated.

Thanks,
Aamir

**Comment by olszomal** [comment]
It works with PKCS11 modules.
You should indicate PKCS11 engine and PKCS11 module.
The way I use it with SoftHSM is:
```` 
./osslsigncode sign \
-pkcs11engine /usr/lib64/engines-1.1/pkcs11.so \
-pkcs11module /usr/lib64/pkcs11/libsofthsm2.so \
-certs cert.pem \
-key 'pkcs11:token=mytoken;object=key' \
-in input.exe -out output.exe
```` 
osslsigncode currently does not support reading certificates from engines.
