### ISSUE TITLE
problem with certificates bundle

### ISSUE THREAD

**Issue by patatetom** [mtrojnar/osslsigncode#355]
hi,

the problem occurs under ArchLinux  but not under Ubuntu.
`osslsigncode` is in the same version on both systems, which is not the case for `openssl`.

- ArchLinux :
```
# osslsigncode --version
osslsigncode 2.7, using:
	OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
	libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0
…

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/MicrosoftRootCertificateAuthority2011.crt.pem
…
Number of verified signatures: 1
✅ Succeeded

# (
echo "# MicrosoftRootCertificateAuthority2011"
cat test/MicrosoftRootCertificateAuthority2011.crt.pem
) > test/test.pem

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/test.pem
…
Number of verified signatures: 1
✅ Succeeded

# (
echo "# MicrosoftRootCertificateAuthority2010"
cat test/MicrosoftRootCertificateAuthority2010.crt.pem
) >> test/test.pem 

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/test.pem
…
Number of verified signatures: 1
❌ Failed
```

- Ubuntu (22.04 LTS) :
```
# osslsigncode --version
osslsigncode 2.7, using:
	OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
…

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/MicrosoftRootCertificateAuthority2011.crt.pem
…
Number of verified signatures: 1
✅ Succeeded

# (
echo "# MicrosoftRootCertificateAuthority2011"
cat test/MicrosoftRootCertificateAuthority2011.crt.pem
) > test/test.pem

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/test.pem
…
Number of verified signatures: 1
✅ Succeeded

# (
echo "# MicrosoftRootCertificateAuthority2010"
cat test/MicrosoftRootCertificateAuthority2010.crt.pem
) >> test/test.pem 

# osslsigncode verify -ignore-timestamp -in test/msedge.exe -CAfile test/test.pem
…
Number of verified signatures: 1
✅ Succeeded
```

regards, lacsaP.

**Comment by mtrojnar** [comment]
You have also confirmed this issue against the GitHub master branch of osslsigncode, haven't you?  Otherwise, you should have reported this issue to the Arch package maintainer rather than here.

IFAIK osslsigncode **only** uses the OS certificate bundle when the `-CAfile` option is **not** specified.  Thus, the issue seems to depend on the OpenSSL version (and unlikely also any patches added by the OS package maintainer) and not the OS certificate bundle.  Can you check which OpenSSL versions are affected?

**Comment by patatetom** [comment]
- yes, but as the issue was closed, I wasn't sure whether my addition would be taken into account and preferred to reopen a new issue.
- in the last scenario I put forward (new issue), I only use the `-CAfile` option to easily vary my test file, which contains one and then two certificates (a tiny bundle), and this can be compared with using the system bundle (previous closed issue). I'm willing to test `openssl`, but how do you see it ?

**Comment by mtrojnar** [comment]
Use this example:
```sh
$ cd ~/src
$ tar -xzf openssl-3.2.1.tar.gz
$ cd openssl-3.2.1
$ ./config --prefix=/opt/openssl-3.2.1
$ make
$ sudo make install
$ cd ~/src/osslsigncode/build
$ LD_LIBRARY_PATH=/opt/openssl-3.2.1/lib64 ./osslsigncode -v
```
Adjust paths to match your local environment and the tested OpenSSL version.  Add your own tests.

**Comment by mtrojnar** [comment]
> I wasn't sure whether my addition would be taken into account

BTW: What do you mean by "my addition" exactly?

**Comment by patatetom** [comment]
I edited the issue (added an exchange) after it was closed.

**Comment by mtrojnar** [comment]
Please use the #number format when referencing other issues to ensure clarity for everyone viewing this issue, not just myself. We prefer to dedicate our time to solving technical problems rather than deciphering references to other issues.

**Comment by mtrojnar** [comment]
The first sentence of my first response to this issue 3 days ago was:

> You have also confirmed this issue against the GitHub master branch of osslsigncode, haven't you?

I'm glad you got it working.
