### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by diaoqi129** [mtrojnar/osslsigncode#369]
when i install bind9.17.1 on my ecs, i run configure and receive that message.
the text not seem to be wrong.
and i have installed pkg-config
so what can i do to fix the problem
`$ aclocal --print-ac-dir
/usr/share/aclocal`

**Comment by mtrojnar** [comment]
What does bind9.17.1 on your ecs have to do with osslsigncode?
