### ISSUE TITLE
Sign powershell scripts (ps1)

### ISSUE THREAD

**Issue by chasewallis** [mtrojnar/osslsigncode#37]
I need to sign ps1 files, but I don't want to have go to a windows machine just to sign a script. Is it possible to modify this program to also sign ps1 files?

A signed ps1 file would just have the signature appended to the end of the script:

```
# SIG # Begin signature block
# thesignaturewouldgohere
# ...
# SIG # End signature block
```

**Comment by olszomal** [comment]
I'm working on this issue. I managed to decode and read the signature from a signed ps1 file.

I wonder how to calculate a hash of this file contents to ensure file integrity?
Do you know the algorithm how to do it?

**Comment by chasewallis** [comment]
No I don't. I tried to figure this out for a while but didn't get very far. I couldn't find any documentation on it.

**Comment by asvoboda** [comment]
+1 to this feature!

I did some digging, and I found https://specterops.io/assets/resources/SpecterOps_Subverting_Trust_in_Windows.pdf, which may be useful. It was written as a red team doc, but it goes pretty in depth and contains some good references that may be useful.

**Comment by ebourg** [comment]
I've implemented PowerShell scripts signing in [Jsign](https://github.com/ebourg/jsign), that may help you understanding the format:

https://github.com/ebourg/jsign/tree/master/jsign-core/src/main/java/net/jsign/script

**Comment by vesubramanian** [comment]
+1 

I would also like this tool to sign ps1 files. Please update when it's implemented.

**Comment by iumysn** [comment]
+

**Comment by SergiusTheBest** [comment]
PS1 hashing algorithm:
1. Check file encoding.
2. If it's ANSI: convert to UTF-16LE and hash the result.
3. If it's UTF-8: convert to UTF-16LE + BOM and hash the result. 
4. If it's UTF-16LE: convert to UTF-16LE + BOM and hash the result.
5. `# SIG` part is stripped from the hash calculation.

**Comment by overag3** [comment]
Very useful feature for sign powershell module before publish
+1

**Comment by jimmy0012** [comment]
@olszomal any luck with this?

**Comment by mtrojnar** [comment]
I think I found the missing piece: https://github.com/andlabs/utf
I'll give it a try.

**Comment by exoosh** [comment]
> PS1 hashing algorithm:
> 
>     1. Check file encoding.
> 
>     2. If it's ANSI: convert to UTF-16LE and hash the result.
> 
>     3. If it's UTF-8: convert to UTF-16LE + BOM and hash the result.
> 
>     4. If it's UTF-16LE: convert to UTF-16LE + BOM and hash the result.
> 
>     5. `# SIG` part is stripped from the hash calculation.

Cool, thanks. But number 2 seems tough to achieve. On Windows with the active code page, sure, but otherwise only something as complex like `iconv` can provide comprehensive conversion from an ANSI code page that cannot be trivially deduced from the data alone. I'd suggest to completely ignore this part and instead document that only files that are in any of the above Unicode encodings can be handled.

@SergiusTheBest do you have any info how -- if at all -- it handles the line endings? This would seem particularly important for the hashing part, no? Since stripping of the `# SIG` part would be ambiguous if `\n`, and `\r\n` would be handled differently. Or am I missing something obvious? Thanks!

**Comment by SergiusTheBest** [comment]
@exoosh 

About number 2: You can limit it to cases where only Latin characters are used. Otherwise you need to know the code page.

About line endings: as far as I remember EOL is removed from the last line of the script before hashing. How it handles `\n`  I don't know. But there are only 2 options: leave it as is or convert to `\r\n`. So it can be checked on practice.

**Comment by exoosh** [comment]
Thanks @SergiusTheBest (I love Vergilius, btw ... thanks for that, too).

**Comment by mtrojnar** [comment]
I started implementing the feature.  It should be ready in a few weeks.

**Comment by ebourg** [comment]
I confirm the charset conversion is tricky. In Jsign a PowerShell script without byte order marks is assumed to be in UTF-8 by default, and the user can change the charset used with an `--encoding` parameter.

For PowerShell XML scripts (.ps1xml) the file is parsed by signtool with the system locale. This produces a signature that is valid on a system with the same locale, but potentially invalid on another system with a different locale.

**Comment by github-user-7** [comment]
Will this also support psd1 and psm1 files when completed?  Thanks for taking this on.

**Comment by ambrisko** [comment]
I was wondering if a few weeks had passed now?  Please let me know if I can help to avoid duplicate efforts.  Doing a grep "# SIG" didn't show anything!

**Comment by mtrojnar** [comment]
About 30% of the functionality is implemented.

My tasks are prioritized as follows:
1. Paid work.
2. Bug fixes.
3. New features.

This particular task currently has the lowest priority.

**Comment by ambrisko** [comment]
What would the cost and calendar time estimate to get it completed be?  Is your current WIP in a branch?  Thanks.

**Comment by mtrojnar** [comment]
I have committed the beta version of the script format support. I welcome testing to ensure any identified issues are resolved before the upcoming release.

**Comment by ambrisko** [comment]
I did a quick sanity check that something happens when I sign a PS file and see a # SIG in the resulting file.  Doing an osslsigncode verify worked on it.  I haven't tried it signing with our cert. and check what Windows says.  Thanks.

**Comment by deamen** [comment]
I tried to sign a "hello, world" PowerShell today:
` .\osslsigncode.exe sign -certs .\test.crt -key .\test.key -n "Hello World" -i https://www.example.com -in .\hello.ps1 -out .\hello-signed.ps1
Script file format: .ps1
Signature position: 0
Succeeded`
But I am getting the prompt:
`Do you want to run software from this untrusted publisher?
File hello-signed.ps1 is published by CN=example.com and is not trusted on your system. Only run scripts from trusted publishers.`

I am using a code signing certificate from HashiCorp Vault, the issuing root CA and intermediate CA are in the "Trusted Root Certification Authorities" and "Intermediate Certification Authorities" certificate store.

When I check the signature of the signed script, the certificate path shows up correctly. And certutil -veirfy test.crt complete successfully. 

Here is the osslsigncode verify output:

> Signer's certificate:
>         ------------------
>         Signer #0:
>                 Subject: /CN=example.com
>                 Issuer : **redacted**
>                 Serial : > 3F27E3DADA5BF956C4BA202F51EB36C7F104BDFB
>                 Certificate expiration date:
>                         notBefore : Feb 19 22:26:34 2024 > GMT
>                         notAfter : Feb 20 22:27:03 2024 > GMT
> 
> Message digest algorithm: SHA256
> 
> Authenticated attributes:
>         Signing time: Feb 19 23:13:42 2024 GMT
>         Microsoft Individual Code Signing purpose
>         Message digest: > C0DEDFEF2D7E838F8BD6851BC772D91B8617D20EB9CEA61F5> F68A5CBD2F1E51A
>         URL description: https://example.com
>         Text description: Hello World
> 
> CAfile: (null)
> 
> Timestamp is not available
> 
> Failed to add store lookup file
> Signature verification: failed
> 
> Number of verified signatures: 1
> Failed

**Comment by mtrojnar** [comment]
> CAfile: (null)
> Failed

It is expected for signature verification to fail in the absence of trusted certificates.
Please clearly indicate if you believe something did not function as anticipated.

**Comment by deamen** [comment]
> It is expected for signature verification to fail in the absence of trusted certificates. Please clearly indicate if you believe something did not function as anticipated.

Sorry, my bad, the issues I had are all user errors.

I confirm signing PowerShell works, thanks for the great work. I am looking forward to the official release.
