### ISSUE TITLE
osslsigncode cmd generates different executables each time

### ISSUE THREAD

**Issue by ganesh-getweave** [mtrojnar/osslsigncode#370]
It's more of a doubt, I was comparing the signed files. 

steps to re-produce..

Use the `osslsigncode` CLI
Create two signed files with the same inputs( same exe file, certs, passkey, etc.,)
Compare the two signed files using `diff` CLI

The `diff` tool returns a message that they differ.

Confirm for me, if the tool generates the same signed files when the inputs are same.

**Comment by ebourg** [comment]
Removing the signing time attribute would help here, it isn't required and harms the reproducibilty. The issue remains for the counter signature though.

**Comment by mtrojnar** [comment]
> Removing the signing time attribute would help here, it isn't required and harms the reproducibilty.

Reproducibility is not an expected feature of digital signatures.

> The issue remains for the counter signature though.

Can you clarify, please?

**Comment by ebourg** [comment]
> Reproducibility is not an expected feature of digital signatures

Reproducible builds are important, even when digital signatures are involved. The solution is to store the signature in a file which is shipped along the source release (either a tarball or in a tagged git repository). When rebuilding the project the signing process imports the detached signature from the file instead of generating a new signature.

**Comment by mtrojnar** [comment]
### About reproducible builds
Reproducible builds are only useful for third parties (not for yourself), thus they require a production signature that does not expire. For the signature to remain valid beyond the expiration of its signing certificate, it needs to include a timestamp. By definition, this timestamp is not reproducible by third parties at a different point in time.

### About the "Timestamp" Value
I realized that it was the "Timestamp" value in the partially visible "test-osslsigncode-signed.appx Properties" window screenshot. This is a bug in Windows, as the printed value is not derived from an actual timestamp, evident in the "Digital Signature Details" window, where the "Countersignatures" table does not contain any timestamp. Feel free to report this bug to Microsoft.

**Comment by ebourg** [comment]
The idea is to export the signature with the counter signature, the full PKCS#7 structure basically. That way the signed+timestamped binary is reproducible.

**Comment by mtrojnar** [comment]
If you copy the entire signature from a previous executable then you don't need signing with osslsigncode.
