### ISSUE TITLE
Hangs in macOS Sonoma 14.0 with latest libs

### ISSUE THREAD

**Issue by SebastianBugna** [mtrojnar/osslsigncode#383]
This was working until I did a brew update, now the osslsigncode just hangs after saying 'Engine "pcks11" set'. 
Already updated osslsigncode to latest version and built again, just in case.
It doesn't output any other error or information. It just hangs. The token is correctly connected and I see the EV (Extended Validation) valid certificate available in the device. Also I can codesign correctly using singtool.exe on other Windows machines.
Using:
- macOS M2 / Sonoma 14.0
- osslsigncode 2.9-dev (also tried osslsigncode 2.8 from brew)
- libp11 0.4.12
- OpenSSL 3.3.1 (Also tried OpenSSL 1.1.1w)

Command used is
$dir"/osslsigncode sign -verbose -pkcs11engine /opt/homebrew/Cellar/libp11/0.4.12/lib/engines-3/pkcs11.dylib  -pkcs11module /usr/local/lib/libeTPkcs11.dylib  -h sha256 -pass 'pass' -in "$1" -out "${1}".EEK -key 8e9a398de48403837f38ee1d2403f3ac -certs "${dir}/cert2025.pem"  -t 'http://timestamp.globalsign.com/?signature=sha2'

I have also tried building osslsigcode 2.9-dev using OpenSSL 1.1.1w, and also using the MacOS brew version (osslsigncode v2.8 which uses OpenSSL 3.3.1) but it doesn't work either.

The README says:   
brew install cmake pkg-config openssl@1.1
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

This means osslsigncode is not working with latest libs, right?
Is there other openssl and pcks11 versions that would work?

**Comment by mtrojnar** [comment]
Please submit a stack backtrace of the hang.  I'm pretty sure it's caused either by your PKCS#11 module (libeTPkcs11.dylib)  or by your PKCS#11 OpenSSL engine (libp11).
