### ISSUE TITLE
Signing with Inno Setup

### ISSUE THREAD

**Issue by thommcgrath** [mtrojnar/osslsigncode#392]
Unless I am mistaken, Inno Setup and osslsigncode are not compatible. Inno Setup requires that the file be signed in-place / overwritten, and osslsigncode refuses to do so. Could an option be added to osslsigncode to allow overwriting the input file so it can be used with Inno Setup?

**Comment by mtrojnar** [comment]
Can Inno Setup execute a script for signing?

**Comment by thommcgrath** [comment]
Yes, and that's my current workaround. It just seems like an unnecessary one.
