### ISSUE TITLE
PKCS11 Clarification on Parameters

### ISSUE THREAD

**Issue by SaltySolomon** [mtrojnar/osslsigncode#40]
I am currently trying to sign an executable with a hsm. I am unsure how the -key parameter works how to define the user to use for connecting to the hsm. I am using a luna safenet network hsm and got it running with pyhsm. But I now need executable suport.

I am currently using the following command:

osslsigncode sign -pkcs11engine /usr/lib64/engines-1.1/pkcs11.so -pkcs11module /usr/safenet/lunaclient/lib/libCryptoki2_64.so -certs ./Certificate.cer -key 0:100 -pass [Password] -verbose -in ./in.exe -out ./out.exe

And I am getting:

Login failed
Login to token failed, returning NULL...
PKCS11_get_private_key returned NULL
Failed to load private key 0:77
140226514693248:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1130:
140226514693248:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:290:Type=PKCS7
140226514693248:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:
Failed

**Comment by olszomal** [comment]
I believe this issue may be helpful #34
