### ISSUE TITLE
Allow specifying blob contents when using -addUnauthenticatedBlob

### ISSUE THREAD

**Issue by tyilo** [mtrojnar/osslsigncode#402]
Instead of just adding the blob `---BEGIN_BLOB---...---END_BLOB---` which can then be replaced with another script, I think it would be more useful if we could specify the contents of the blob.

Something like
```
$ echo foo > blob.txt
$ osslsigncode add -addUnauthenticatedBlob blob.txt -in foo.exe -out foo-blob.exe
```

**Comment by mtrojnar** [comment]
Would you submit a PR?

**Comment by tyilo** [comment]
> Would you submit a PR?

I'm going on vacation so it might be a while, but after that sure.

Do you think it is ok to make `-addUnauthenticatedBlob` require a path?

**Comment by mtrojnar** [comment]
> Do you think it is ok to make `-addUnauthenticatedBlob` require a path?

Your PR should not break any existing scripts that invoke osslsigncode, so `-addUnauthenticatedBlob` should not **require** a path.
