### ISSUE TITLE
Trying to run from inside a lambda

### ISSUE THREAD

**Issue by KaceyHaley-LG** [mtrojnar/osslsigncode#406]
Hey all,

I am attempting to run this binary from within a serverless function. Using v2.6 I am getting.
`/tmp/osslsigncode: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`

I don't think the latest has the libcurl dependency? I could be wrong there. Any advice is more than welcome! Thanks!

**Comment by mtrojnar** [comment]
Do not use v2.6.
