### ISSUE TITLE
verify signed code using certs on a pkcs11 token?

### ISSUE THREAD

**Issue by oxelson** [mtrojnar/osslsigncode#415]
Apologies if this query should go elsewhere! 

We were able to sign .msi and .exe files using certs stored on a pkcs11 token.  Is there a way to run the verify command against the certs stored on the token?  I'm not seeing how to access the token with the options given for the verify command:

```
 verify [ -in ] <infile>
            [ -c | -catalog <infile> ]
            [ -CAfile <infile> ]
            [ -CRLfile <infile> ]
            [ -HTTPS-CAfile <infile> ]
            [ -HTTPS-CRLfile <infile> ]
            [ -TSA-CAfile <infile> ]
            [ -TSA-CRLfile <infile> ]
            [ -p <proxy> ]
            [ -index <index> ]
            [ -ignore-timestamp ]
            [ -ignore-cdp ]
            [ -ignore-crl ]
            [ -time <unix-time> ]
            [ -require-leaf-hash {md5,sha1,sha2(56),sha384,sha512}:XXXXXXXXXXXX... ]
            [ -verbose ]
```

**Comment by mtrojnar** [comment]
Verification is not performed against individual leaf (end-entity) certificates but rather against the chain of trust originating from a trusted root CA certificate. Storing trusted CA certificates on a hardware device offers no security advantage when the verification is conducted in software.
