### ISSUE TITLE
Signing with more than 2 signatures

### ISSUE THREAD

**Issue by asvoboda** [mtrojnar/osslsigncode#42]
Hi,

I have a slightly weird use-case: dual sign a PE with multiple certificates in both sha1 and sha256. This works "fine" with signtool.exe, and I'm wondering how to best approach this with osslsigncode. 

I'd want to be able to continue appending nested signatures using `-nest`, although I don't mind if I need to change the arguments to get this working. However, in practice it looks like osslsigncode just overwrites the signature that was nested, so I only ever end up with the first (non nested signature) and the last nested signature.

Example:
```
osslsigncode sign -h sha1 \
  -certs cert.pem -key key.pem -pass pass
  -in foo.exe -out foo.1.exe

osslsigncode sign -h sha256 \
  -nest
  -certs cert.pem -key key.pem -pass pass
  -in foo.1.exe -out foo.2.exe

osslsigncode sign -h sha256 \
  -nest
  -certs othercert.pem -key otherkey.pem -pass otherpass
  -in foo.2.exe -out foo.3.exe
```

Then on verify:
```
osslsigncode verify -in foo.3.exe

expected: <3 signatures>
actual: <2 signatures, missing the sha256 signature from cert.pem>
```

It looks like the tests currently use just two, https://github.com/mtrojnar/osslsigncode/blob/master/tests/recipes/11_sign_nest, and I can correctly get dual signing to work with just two, but no more. Am I missing options for signing with multiple certificates?

**Comment by mtrojnar** [comment]
Could you please provide us with documentation for the signature format supporting more than two signatures?
Do you know other tools that support it?

**Comment by asvoboda** [comment]
As far as I can tell, this behaviour "just works" with signtool.exe, but otherwise appears to be poorly documented. I'll try to find some more information for you.

**Comment by asvoboda** [comment]
`signtool.exe` has the option `/as` for appending, similar to `-nest` in osslsigncode. It doesn't seem to be explicit about it, but that can be used to sign multiple times with different certificates.
