### ISSUE TITLE
libgsf is not available, msi support is disabled: test.msi, while signing msi

### ISSUE THREAD

**Issue by AamirZahid** [mtrojnar/osslsigncode#46]
trying to sign MSI on centOS 7 with subjected error:

[root@localhost 64]# osslsigncode sign -certs ossl.pem -key privkey.pem -in test.msi -out sign.msi
Enter PEM pass phrase:
libgsf is not available, msi support is disabled: test.msi
140163159205808:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140163159205808:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:649:
140163159205808:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140163159205808:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=RSA
140163159205808:error:04093004:rsa routines:OLD_RSA_PRIV_DECODE:RSA lib:rsa_ameth.c:121:
140163159205808:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140163159205808:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=PKCS8_PRIV_KEY_INFO
140163159205808:error:0907B068:PEM routines:PEM_READ_BIO_PRIVATEKEY:bad password read:pem_pkey.c:117:

osslsigncode -v
osslsigncode 1.7.1, using:
	OpenSSL 1.0.2k-fips  26 Jan 2017
	libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
	no libgsf available

yum install libgsf
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.piconets.webwerks.in
 * extras: mirrors.piconets.webwerks.in
 * updates: mirrors.piconets.webwerks.in
Package libgsf-1.14.26-7.el7.x86_64 already installed and latest version
Nothing to do

Let me know if I am missing something?

Thanks for the help...

**Comment by mtrojnar** [comment]
libgsf not only needs to be available when running osslsigncode, but also when configuring/building it.  Try rebuilding osslsigncode from scratch.  Include the output of ./configure and your config.log if it still cannot find libgsf.
