### ISSUE TITLE
failed with 64 bits binaries

### ISSUE THREAD

**Issue by backupPG** [mtrojnar/osslsigncode#49]
I tried to sign 64 bits binaries and the exe won't work anymore

**Comment by olszomal** [comment]
I could not replicate this issue. It works for me on Windows 10.
It seems to be a problem with a deployed code-signing policy. Please check your Software Restriction Policies, AppLocker and antivirus.
If it still fails, please help me replicate this issue. Could you share a publicly available executable which stopped working after signing?

**Comment by mtrojnar** [comment]
The requestor provided no way to replicate this issue.
