### ISSUE TITLE
Signing APPX/MSIX Packages

### ISSUE THREAD

**Issue by nephatrine** [mtrojnar/osslsigncode#51]
osslsigncode does not recognize the .appx/.msix file types and is unable to sign them. I'm building them using the makemsix tool from the [MSIX sdk](https://github.com/microsoft/msix-packaging), but does not (yet) provide a way to sign them and it's not trivial to install an unsigned msix package on Windows as it is for .exe and .msi so there's almost no point bothering with them without that capability. The sdk does have code relating to verifying the signatures in their [unpacking code](https://github.com/microsoft/msix-packaging/blob/master/src/msix/unpack/AppxSignature.cpp) and there is WIP [signing code](https://github.com/microsoft/msix-packaging/blob/johnmcpms/signing/src/msix/pack/Signing.cpp) in another branch, but it's not really in a usable state yet. Their code is MIT so I'd imagine there shouldn't be any trouble cribbing from it to implement this sort of things in osslsigncode, but I do not know how much effort would be involved or whether you're even interested.

**Comment by ebourg** [comment]
I've started looking into the MSIX format for [Jsign](https://github.com/ebourg/jsign), I've posted some technical information that may be useful to implement it in osslsigncode:

https://github.com/ebourg/jsign/issues/81#issuecomment-655988538

**Comment by bhearsum** [comment]
> osslsigncode does not recognize the .appx/.msix file types and is unable to sign them. I'm building them using the makemsix tool from the [MSIX sdk](https://github.com/microsoft/msix-packaging), but does not (yet) provide a way to sign them and it's not trivial to install an unsigned msix package on Windows as it is for .exe and .msi so there's almost no point bothering with them without that capability. The sdk does have code relating to verifying the signatures in their [unpacking code](https://github.com/microsoft/msix-packaging/blob/master/src/msix/unpack/AppxSignature.cpp) and there is WIP [signing code](https://github.com/microsoft/msix-packaging/blob/johnmcpms/signing/src/msix/pack/Signing.cpp) in another branch, but it's not really in a usable state yet. Their code is MIT so I'd imagine there shouldn't be any trouble cribbing from it to implement this sort of things in osslsigncode, but I do not know how much effort would be involved or whether you're even interested.

For what it's worth, I've been able to make that branch sign an MSIX with:
```
makemsix pack -p myfile.msix -d dir
makemsix sign -p myfile.msix -c mycert.pfx
```

There's a couple of complications:
1) It only seems to work with files packed by `makemsix`. I had to unpack an existing msix with `zip`, and repack it with the above command
2) It only supports pfx (pkcs12) bundles with absolutely no traces of passphrases in them. These can be made with `openssl pkcs12 -export -out mycert.pfx -inkey my.key -in my.pem -keypbe NONE -certpbe NONE -nomaciter`.

**Comment by karlvr** [comment]
Is there any interest from anyone on working on this? I'd like it and I'd considering sponsoring some development!

**Comment by mtrojnar** [comment]
> Is there any interest from anyone on working on this? I'd like it and I'd considering sponsoring some development!

Sounds great.  I couldn't find any contact info in your GitHub bio, so please drop me a line at Michal.Trojnara@stunnel.org.

**Comment by mtrojnar** [comment]
We investigated this issue.  The reason no other project has implemented this feature yet is not insufficient effort, but rather insufficient documentation.  While https://github.com/microsoft/msix-packaging/tree/johnmcpms/signing is technically hosted on Microsoft's GitHub account, it suffers from missing documentation as well.

There is nothing we can do until we get the missing documentation.

**Comment by ebourg** [comment]
The technical details are now documented: https://github.com/ebourg/jsign/wiki/MSIX-APPX-signing

@panekmaciej is working on an implementation for osslsigncode: https://github.com/panekmaciej/osslsigncode/blob/appx/appx.c
