### ISSUE TITLE
Sign catalog files

### ISSUE THREAD

**Issue by chriscla** [mtrojnar/osslsigncode#52]
It would be great if osslsigncode could sign catalog files. We are able to generate a valid catalog file but won't have a windows machine available to sign it.   I haven't yet found a Linux alternative to signtool for signing catalogs.

**Comment by mtrojnar** [comment]
You mean .cat files for Windows kernel drivers, right?  Do you have any documentation for the signature format?

**Comment by chriscla** [comment]
Yes, windows catalog files for drivers or for putting together catalogs for Windows Defender Application Control.  I wish I had documentation but it doesn't appear to be documented :(

There has been some research: 

https://blog.cryptomilk.org/2016/10/25/hack-ms-catalog-files-and-digital-signatures/
https://blogs.gnome.org/hughsie/2015/07/14/building-a-better-catalog-file/

This research goes into how to actually parse the catalog from scratch. Perhaps adding a signature to an existing catalog would be much simpler?

**Comment by chriscla** [comment]
This is so cool. Thank you!

**Comment by chriscla** [comment]
This works for us. Is there any chance that you can do a new release that includes this change?  We would prefer not to pick up a master version.  Thanks again @mtrojnar and @olszomal!
