### ISSUE TITLE
Detached signature output?

### ISSUE THREAD

**Issue by jenskutilek** [mtrojnar/osslsigncode#53]
OpenType fonts can be digitally signed. They may contain a [DSIG table](https://docs.microsoft.com/en-us/typography/opentype/spec/dsig) in the SFNT structure for this purpose. To apply a signature, I would need a separate PKCS#7 blob containing the signature. Adding it to the font can be done with existing tools, e.g. the [Python FontTools](https://github.com/fonttools/fonttools/) as a lot of fonts are built using Python today.

Any chance that osslsigncode could support output of detached signatures?

MS's `signtool.exe` can be used to sign fonts when you have `mssipotf.dll` which is hard to get hold of. It would be great to have an alternative.

**Comment by ebourg** [comment]
Do you have a sample of a detached signature for a font?

**Comment by mtrojnar** [comment]
Concatenating the described DSIG headers with a DER output from [`openssl pkcs7`](https://www.openssl.org/docs/man1.1.1/man1/pkcs7.html) should be fairly trivial.  Implementing this in osslsigncode seems like an overkill.

**Comment by jenskutilek** [comment]
I’ve researched this some more, and the OpenType spec doesn’t state all the requirements of the signature inside the PKCS#7 blob. As far as I know, Windows, respectively the MS Font Validator are the only tools that can validate a DSIG table. They expect an Authenticode signature with timestamp, similar to a CAB signature. This is not specified anywhere, I just found out by analyzing a signature generated by signtool.exe with mssipotf.dll.

Font signatures are not very common. I know some of the biggest manufacturers use them, but pretty much no one else does.

So maybe this isn’t worth any implementation effort.

If you’re interested, I can still upload a sample next week.

**Comment by jenskutilek** [comment]
Here is a sample zip.

* `KoningDisplay-Black_TRIAL.otf` the font without DSIG table
* `KoningDisplay-Black_TRIAL_DSIG.otf` the font with DSIG table, signed with `signtool.exe`
* `KoningDisplay-Black_TRIAL_DSIG.bin` the binary data of the DSIG table incl. DSIG headers
* `KoningDisplay-Black_TRIAL.p7b` just the PKCS#7 blob (detached signature)

[DSIG-Test.zip](https://github.com/mtrojnar/osslsigncode/files/4948670/DSIG-Test.zip)

The digest of the font file is calculated from the file as-is (without DSIG table) first, then updated with the bytes `00 01` for some (undocumented) reason. The OpenType spec says to _Zero out the file checksum in the ‘head’ table_ prior to calculating the file digest, which is also not true ;)

**Comment by ebourg** [comment]
Windows doesn't show the digital signature tab in the properties of the signed font, is this normal?

**Comment by jenskutilek** [comment]
Usually it should be there ...

![Screenshot 2021-07-20 at 16 39 01](https://user-images.githubusercontent.com/3185950/126343499-a7643722-b7d5-4b09-ae10-d8bf7f56fa67.png)

**Comment by jenskutilek** [comment]
I've done some more research on font signatures. The actual calculation of the digests etc. is fairly trivial, but the few tools that will validate a font signature expect a very specific format of the PKCS#7 blob that is similar to Authenticode signatures, but is not well documented. One would need to analyze the ASN1 structure of existing signatures very closely.

I don't think it's worth the effort, as signing fonts never got much traction.

**Comment by ebourg** [comment]
@jenskutilek Do you remember how you managed to get the 'Digital Signatures' tab on signed fonts?

I've downloaded `mssipotf.dll` from https://learn.microsoft.com/en-us/typography/tools/signing-tool/dsig.zip, copied the dll to `C:\Windows\System32`, and then registered it with `regsvr32 mssipotf.dll`, but it doesn't work. The tab doesn't appear in the file properties, and signtool doesn't see the signature either.

**Comment by ebourg** [comment]
@jenskutilek I confirm it works on Windows 10, thank you very much!

I now realize that the 32 bit DLL may work too if I installed in `C:\Windows\SysWOW64` and registered with the version of `regsvr32` in this directory.
