### ISSUE TITLE
[2.1] build fails using static openssl

### ISSUE THREAD

**Issue by tuxmaster5000** [mtrojnar/osslsigncode#62]
When using an static version of openssl it looks like the configure script don't detect the needed linker options correct, so it fails with:

> gcc -I/usr/include/libgsf-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2   -I/builddir/build/BUILD/my_openssl/include    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wl,-z,relro  -o osslsigncode osslsigncode.o -lgsf-1 -lgobject-2.0 -lxml2 -lglib-2.0   -L/builddir/build/BUILD/my_openssl/lib -lcrypto   -lcurl   
> /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libgsf-1.so: undefined reference to symbol 'deflate'
> //usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
> make[1]: Leaving directory `/builddir/build/BUILD/osslsigncode-2.1'
> collect2: error: ld returned 1 exit status
> make[1]: *** [osslsigncode] Error 1
> make: *** [all] Error 2

Workaround:

> LDFLAGS="$RPM_LD_FLAGS -lz -ldl -pthread" ./configure ....

**Comment by olszomal** [comment]
This issue may be closed if no further activity occurs.

**Comment by mtrojnar** [comment]
Indeed.  We no longer depend on libgsf, so we don't have to worry about its dependencies.
