### ISSUE TITLE
Code signing suddenly stopped working

### ISSUE THREAD

**Issue by AllinCottrell** [mtrojnar/osslsigncode#70]
I've been happily signing exe's with a Digicert certificate and osslsigncode for several years, with an invocation of

`osslsigncode sign -certs certificate.cer -key private.rsa.pem ...`

But today it stopped working, with the errors shown below. libssl and libcrypto have been updated fairly recently on my Arch system, but signing has worked OK since then so I don't think that can be the issue. The cert files I'm using are unchanged. Any ideas what could be happening here? (I've googled those errors and the standard analysis seems to be that the cert file(s) are malformed, with unwanted whitespace, but these files of mine have been working for years.)

`error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:`
`error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:572:`
`error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:`
`error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1tasn_dec.c:309:Type=RSAPrivateKey`
`error:04093004:rsa routines:old_rsa_priv_decode:RSA lib:crypto/rsa/rsa_ameth.c:142:`
`error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:`
`error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:309:Type=PKCS8_PRIV_KEY_INFO`
`error:02001011:system library:fopen:File exists:crypto/bio/bss_file.c:69:fopen('Output/gretl_install-64.exe','w+bx')`
`error:2006D002:BIO routines:BIO_new_file:system lib:crypto/bio/bss_file.c:78:`

**Comment by AllinCottrell** [comment]
A little more info, in case it helps. I've been using osslsigncode 1.7.1 but on seeing this problem I updated to 2.1.0. That didn't make any difference. Also, I'm using a SHA2 cert from Digicert that is supposed to be good till June 2021.

**Comment by mtrojnar** [comment]
```
error:02001011:system library:fopen:File exists:crypto/bio/bss_file.c:69:fopen('Output/gretl_install-64.exe','w+bx')
```
osslsigncode does not automatically remove the output file before creating a new one.  Simply remove your previous `Output/gretl_install-64.exe` file and try again.

**Comment by trdyer** [comment]
If you are using timestamps as part of your digital signature the root cause may be that verisign has killed their timestamp server.

**Comment by AllinCottrell** [comment]
@mtrojnar : Thanks, that did it! I'm still not sure how the difference arose, relative to when it was working fine previously.

@trdyer : That possibility occurred to me too. I tried my script without the time-stamp clause but that in itself didn't solve the problem.
