### ISSUE TITLE
Support for XKU_CODE_SIGN purpose or note why what's not supported

### ISSUE THREAD

**Issue by Jaakkonen** [mtrojnar/osslsigncode#77]
I'm checking Debian secure boot shim signatures.
Shim itself is signed by Microsoft and trusts a Debian Secure Boot CA cert.
Certificate: https://dsa.debian.org/secure-boot-ca
Shim: https://salsa.debian.org/pmhahn/shim-signed/-/blob/master/shimx64.efi.signed

The shim can be checked against microsoft key with `sbverify`.

However when I try checking the signature of `mmx64.efi` and `fbx64.efi` from [shim-helpers-amd64-signed](https://deb.debian.org/debian/pool/main/s/shim-helpers-amd64-signed/shim-helpers-amd64-signed_1+15+1533136590.3beb971+10_amd64.deb) I get `sbverify` failing as it's signed with other certificate which is issued by this CA.

`osslsigncode verify -CAfile debian-secure-boot-ca.pem usr/lib/shim/fbx64.efi.signed` should work but the signer has purpose `XKU_CODE_SIGN` which is not supported. I'm not sure why that's not allowed and cannot find any information for what that extension is used for. I think a comment should be added into the code reasoning why it's not allowed and the error print made a bit more clear.

**Comment by Jaakkonen** [comment]
Found [uthenticode](https://github.com/trailofbits/uthenticode) library to do the `CODE_SIGN` purpose aka Authenticode PE executable verification. As a workaround with `osslsigncode` I extracted the signature of the file, printed the PKCS7 certificates and verified those against the trusted CA. However I'm not sure if the PKCS7 certificates can be altered without `osslsigncode` warning on that or if the signature is actually checked against the file contents.

```
osslsigncode extract-signature -pem usr/lib/shim/fbx64.efi.signed fbx64.sig
openssl pkcs7 -print_certs -in fbx64.sig | tail -n +5 > fbx64.pem
openssl verify -CAfile debian-secure-boot-ca.pem fbx64.pem
```

**Comment by olszomal** [comment]
[RFC5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.12):
_If the extension is present, then the certificate MUST only be used for one of the purposes indicated._ 

Signing of downloadable executable code expects **X509v3 Extended Key Usage: Code Signing** purpose.

Files `mmx64.efi` and `fbx64.efi` are signed with a certificate with **X509v3 Extended Key Usage: Microsoft Trust List Signing**
```
$ openssl pkcs7  -in ./fbx64.pem -print_certs -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3042882489 (0xb55eb3b9)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Debian Secure Boot CA
        Validity
            Not Before: Jul 21 15:52:54 2020 GMT
            Not After : Jul 21 15:52:54 2030 GMT
        Subject: CN=Debian Secure Boot Signer 2020
...
        X509v3 extensions:
            Netscape Cert Type:
                Object Signing
            X509v3 Extended Key Usage:
                Microsoft Trust List Signing
            X509v3 Key Usage:
                Digital Signature
...
```
Neither `uthenticode` nor `openssl verify` checks any Extended Key Usage.

But [sbverify](https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/tree/src/sbverify.c#n209) does:
```
$ sbverify -v ./fbx64.efi.signed 
warning: data remaining[1054576 vs 1207944]: gaps between PE/COFF sections?
signature 1
image signature issuers:
 - /CN=Debian Secure Boot CA
image signature certificates:
 - subject: /CN=Debian Secure Boot Signer 2020
   issuer:  /CN=Debian Secure Boot CA
PKCS7 verification failed
139988470682752:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:crypto/pkcs7/pk7_smime.c:284:Verify error:unsupported certificate purpose
Signature verification failed
```
Microsoft [signtool ](https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool) as well:
```
>signtool verify /pa /v fbx64.efi.signed
Verifying: fbx64.efi.signed

Signature Index: 0 (Primary Signature)
Hash of file (sha256): E161B25575A9575C7C340B225897A543493D9C6606E1DD3CFA8DAA5009D89E4D

Signing Certificate Chain:
    Issued to: Debian Secure Boot CA
    Issued by: Debian Secure Boot CA
    Expires:   Thu Aug 09 19:09:18 2046
    SHA1 hash: 53610CF81FBD7E0CEB67913C9EF3E794A9633ECB

        Issued to: Debian Secure Boot Signer 2020
        Issued by: Debian Secure Boot CA
        Expires:   Sun Jul 21 16:52:54 2030
        SHA1 hash: 236ACB7F11857DE5907845B34301C83BDE079A4A

File is not timestamped.

SignTool Error: The signing certificate is not valid for the requested usage.

Number of files successfully Verified: 0
Number of warnings: 0
Number of errors: 1 

```
Therefore this `osslsigncode` behavior is correct and intentional.
```
Unsupported Signer's certificate purpose XKU_CODE_SIGN
Signature verification: failed 
```

**Comment by Jaakkonen** [comment]
Ok so essentially this is Debian team signing the executables with X509 certificates with extended key usage in place and "Code Signing" missing from that. Essentially they're using a invalid certificate for this job.

**Comment by mtrojnar** [comment]
@Jaakkonen If you decide to open an issue in their bug tracking system, please also link it here.  I'd be glad to know whether they have a good reason for violating RFC 5280 or it's an honest mistake.
