### ISSUE TITLE
CAB nested signature

### ISSUE THREAD

**Issue by KAZAHTIP2007** [mtrojnar/osslsigncode#80]
I'm use osslsigncode package for Debian Buster ( https://packages.debian.org/buster/osslsigncode )

If I'm attempt attach a nested signature to CAB file I'm got error "**Cannot sign cab files with flag bits set!**".
But .exe/.dll/etc works good.

**Comment by olszomal** [comment]
Please try osslsigncode 2.1 release with improved CAB signature support.
