### ISSUE TITLE
PVK.zip not loading

### ISSUE THREAD

**Issue by hamarb123** [mtrojnar/osslsigncode#84]
Hi,
The link http://support.globalsign.net/en/objectsign/PVK.zip is not loading for me.
I'm getting the DNS_PROBE_FINISHED_NXDOMAIN Check if there is a typo in support.globalsign.net error.
Not sure if this is on my end or not, and if it is, how to fix it.

**Comment by mtrojnar** [comment]
Why exactly do you think we can help you with this website?  Do we have that link somewhere in our documentation? Where?

**Comment by hamarb123** [comment]
Hi, it's in your readme in [this](https://github.com/mtrojnar/osslsigncode/blob/master/README.md#converting-from-pvk-to-der) section.

**Comment by mtrojnar** [comment]
It looks like they moved the file to: http://www.globalsign.com/support/code-signing/PVK.zip
I'll update the link. Thank you for reporting this issue.

**Comment by hamarb123** [comment]
Thank you for that!
(Unrelated to this issue) Hi, I'm failing to get it to run now, do you think you could help me?
I'm running `osslsigncode sign -certs "/Volumes/Hamish 4TB/Hamish Arblaster/Software/Cert/Key.p7b" -key "/Volumes/Hamish 4TB/Hamish Arblaster/Software/Cert/Key.der" -pass "" -h sha512 -n "2DCraft" -t http://timestamp.digicert.com -in "/Volumes/Hamish 4TB/Hamish Arblaster/Software/Code/All/2DCraft/2DCraft.WinForms/bin/Debug/net5.0-windows - Copy (2)/2DCraft.dll" -out "/Volumes/Hamish 4TB/Hamish Arblaster/Software/Code/All/2DCraft/2DCraft.WinForms/bin/Debug/net5.0-windows - Copy (2)/2DCraft.signed.dll"`
and getting `zsh: segmentation fault  osslsigncode sign -certs  -key  -pass "" -h sha512 -n "2DCraft" -t  -in  -out` on my Mac.
