### ISSUE TITLE
An input file can’t be an output file

### ISSUE THREAD

**Issue by olszomal** [mtrojnar/osslsigncode#9]
### Steps to reproduce the bug

I tried to sign a PE file to add a signature to the input file:
```
osslsigncode sign -certs cert.pem -key key.pem -in myapp.exe -out myapp.exe
Bus error (core dumped)
```

The file is damaged after this operation:
```
$ du  myapp.exe
0    myapp.exe
```

The other osslsigncode options (extract-signature, remove-signature, attach-signature) work similarly.

### My initial analysis

The stack backtrace from the gdb tool:
```
#0  0x0000000000403fc2 in main (argc=<optimized out>, argv=<optimized out>)
    at osslsigncode.c:2964
```

**Comment by jenniferrs** [comment]
Does this fix included in OsslSignCode latest version ? What is the workaround that needs to be implemented to get this working.
Please help.

**Comment by mtrojnar** [comment]
Just to be sure: By "working" you mean "reporting an error rather than crashing", right?

**Comment by jenniferrs** [comment]
No.I meant that it will sign if output file is same as input file

**Comment by mtrojnar** [comment]
Don't do it.  osslsigncode opens the input file for reading, and the output file for writing.  It would overwrite its own input if the same file is was used for input and output.

Rename your input file first, and then run osslsigncode.

**Comment by jenniferrs** [comment]
But in my requirement it should sign the same input file. If we take Microsoft SignTool it will sign the input file without asking for another output file

**Comment by mtrojnar** [comment]
Don't hesitate to use Microsoft SignTool instead.

**Comment by jenniferrs** [comment]
I have a requirement where I need to sign files on Linux environment . Is there any workaround for this ? Thanks much.

**Comment by mtrojnar** [comment]
The workaround is either to:
 - Rename your input file to a temporary file, sign it with osslsigncode, and then remove the temporary file.
 - Create a temporary file with osslsigncode, remove the original file, and then rename the temporary file to your original file.
