### ISSUE TITLE
osslsigncode -ph option not specified for PE file injects an "<<<Obsolete>>>" link

### ISSUE THREAD

**Issue by phylasnier-spirent** [mtrojnar/osslsigncode#95]
We're using osslsigncode 2.1, but this occurs with 2.0 too.
We call osslsigncode to sign Windows EXEs (PE files) without specifying the "-ph" option (page hash).
Doing so adds a Unicode string "`<<<Obsolete>>>`" in the signed output. This seems to correspond a string value of the output of get_obsolete_link(), and that "link" gets added to data that would be output, for PE file type, if the "page hash" option is not specified. That "link" is injected by get_indirect_data_blob() (circa line 1604 in osslsigncode.c).

Windows SignTool doesn't do any of that; there's no tell-tale "`<<<Obsolete>>>`" in the output (although this might be something different with SignTool that I haven't spotted).

Would that be a bug, albeit minor ("Obsolete" can be an ominous word), or some correct (and harmless) behaviour?

**Comment by olszomal** [comment]
I think this `<<<Obsolete>>>` value is get from Microsoft's documentation, Windows Authenticode Portable Executable Signature doc, page 11: [ http://download.microsoft.com/download/authenticode_pe.docx]( http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/authenticode_pe.docx)

_**SPCLink** originally contained information that describes the software publisher, but it now has the following choices:_
- **url [0]**
_This choice is not supported, but it does not affect signature verification if present._
- **moniker [1]**
_This choice is set to an SpcSerializedObject structure, which is described later._
- **file [2]**
_This is the default choice. It is set to an SpcString structure, which contains a Unicode string set to `<<<Obsolete>>>`.`_

**Comment by phylasnier-spirent** [comment]
Hmm, you're right @olszomal, thanks. However, for a PE file, the SpcLink in question is in SpcPeImageData, and if the "-ph" option is not specified, we then have `SpcPeImageData.file(SpcLink).file(SpcString)="<<<Obsolete>>>"`. When "-ph" is specified, a page hash is calculated and inserted in `SpcPeImageData.file(SpcLink).moniker(SpcSerializedObject)`. 

Considering that with SignTool (I've used the ClickOnce\SignTool\signtool.exe version), and not using "-ph" either, "Obsolete" doesn't appear, I am wondering if the difference is because the SignTool:

- does not insert a `SpcIndirectDataContent.data(SpcAttributeTypeAndOptionalValue).value(SpcPeImageData)` (which is marked OPTIONAL in the doc's ASN.1 definition of SpcAttributeTypeAndOptionalValue)
- or does not insert a `.value(SpcPeImageData).file(SpcLink)` (the doc on page 10 says it's always set "even though the ASN.1 definitions designate file as optional.")

Considering that the doc is from 2008, things might have changed in a more up-to-date version (and possibly one that Microsoft haven't made public).

This makes osslsigncode behave differently from SignTool. I'm happy that it's probably harmless in this case, and I haven't got the time to dig deeper to answer the question above.

Do you concur? Any further comment? Anyone else?

**Comment by mtrojnar** [comment]
The goal for this project is to implement valid Authenticode signing and verification.  We do not attempt to emulate SignTool.

**Comment by phylasnier-spirent** [comment]
@mtrojnar, the project's own description is "_osslsigncode is a small tool that implements part of the functionality of the Microsoft tool signtool.exe - more exactly the Authenticode signing and timestamping_". Authenticode is a Microsoft code-signing technology; the "Windows Authenticode Portable Executable Signature Format" document is a Microsoft specification; SignTool is Microsoft's code-signing tool.

So the project might not attempt to emulate SignTool, as you write, but at least for Windows binaries, that's the gold standard (however flawed that might be) and the only thing to compare against—which is what I did.
