### ISSUE TITLE
Failed to extract current message digest

### ISSUE THREAD

**Issue by Kcchouette** [mtrojnar/osslsigncode#96]
Hello

I'm trying to use your software to verify a exe signature, in this way:
```bash
$ osslsigncode verify "soft.exe"
```

The software returns me this message:

```
Current PE checksum   : 00000000
Calculated PE checksum: 0C423E31

Failed to extract current message digest

Failed
```

Sadly I didn't find a way to give you more information (`-verbose` is not available for verify) and I can't give you the exe file

I'm trying to patch a bit the files, I'll keep you informed.
Thanks

**Comment by Kcchouette** [comment]
I forget to give you some useful information: 
 - I've tested the ubuntu package version
```
$ osslsigncode --version
osslsigncode 1.7.1, using:
	OpenSSL 1.1.1f  31 Mar 2020
	libcurl/7.68.0 GnuTLS/3.6.15 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.41.0 librtmp/2.3
	libgsf 1.14.47
```

 - and then test on archlinux based on commit 1c175c43393b7f22e3591f6fd757180475329bdc (same message above)
```
osslsigncode 2.1.0, using:
    OpenSSL 1.1.1k  25 Mar 2021 (Library: OpenSSL 1.1.1k  25 Mar 2021)
    libcurl/7.76.1 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0
```

**Comment by olszomal** [comment]
This is really interesting. But I must reproduce myself this issue and research the file.
Could you find or generate similar but not confidential signed PE file and share it?

**Comment by Kcchouette** [comment]
Hello
I fully reproduced the issue with another more available software : atlassian confluence
I'm using install4j to sign the executable like them, and base of the cert is digicert

You can find exe file here: https://www.atlassian.com/software/confluence/download
then I choose "Latest release", OS "windows 64 bit", get started
then I agree the term
And I have the file `atlassian-confluence-7.12.0-x64.exe`

---

without my patch:
```
$ osslsigncode verify atlassian-confluence-7.12.0-x64.exe 
Current PE checksum   : 00000000
Calculated PE checksum: 2E3F659F

Failed to extract current message digest

Failed
```
---
with my patch it shows more information (but *digest mismatch*)
